// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: fleetly/server/v1/alerting.proto

package serverv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/fleetlyrun/fleetly/genproto/fleetly/annotations/v1"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AlertRuleView 是一条规则的读面投影。
type AlertRuleView struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Expr  string                 `protobuf:"bytes,3,opt,name=expr,proto3" json:"expr,omitempty"`
	// for 子句秒数（0 = 无 for 子句）。
	ForDurationSeconds int64 `protobuf:"varint,4,opt,name=for_duration_seconds,json=forDurationSeconds,proto3" json:"for_duration_seconds,omitempty"`
	// 规则 label 集（含 severity——severity 进通知文案的源头）。
	Labels map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 通知端点 id 集（空 = 缺省投全部启用端点）。
	Channels      []string               `protobuf:"bytes,6,rep,name=channels,proto3" json:"channels,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertRuleView) Reset() {
	*x = AlertRuleView{}
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertRuleView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertRuleView) ProtoMessage() {}

func (x *AlertRuleView) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertRuleView.ProtoReflect.Descriptor instead.
func (*AlertRuleView) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_alerting_proto_rawDescGZIP(), []int{0}
}

func (x *AlertRuleView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlertRuleView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlertRuleView) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

func (x *AlertRuleView) GetForDurationSeconds() int64 {
	if x != nil {
		return x.ForDurationSeconds
	}
	return 0
}

func (x *AlertRuleView) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AlertRuleView) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *AlertRuleView) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AlertRuleView) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateAlertRuleRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Expr               string                 `protobuf:"bytes,2,opt,name=expr,proto3" json:"expr,omitempty"`
	ForDurationSeconds int64                  `protobuf:"varint,3,opt,name=for_duration_seconds,json=forDurationSeconds,proto3" json:"for_duration_seconds,omitempty"`
	Labels             map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Channels           []string               `protobuf:"bytes,5,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateAlertRuleRequest) Reset() {
	*x = CreateAlertRuleRequest{}
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertRuleRequest) ProtoMessage() {}

func (x *CreateAlertRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateAlertRuleRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_alerting_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAlertRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAlertRuleRequest) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

func (x *CreateAlertRuleRequest) GetForDurationSeconds() int64 {
	if x != nil {
		return x.ForDurationSeconds
	}
	return 0
}

func (x *CreateAlertRuleRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateAlertRuleRequest) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

type CreateAlertRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *AlertRuleView         `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertRuleResponse) Reset() {
	*x = CreateAlertRuleResponse{}
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertRuleResponse) ProtoMessage() {}

func (x *CreateAlertRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertRuleResponse.ProtoReflect.Descriptor instead.
func (*CreateAlertRuleResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_alerting_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAlertRuleResponse) GetRule() *AlertRuleView {
	if x != nil {
		return x.Rule
	}
	return nil
}

type ListAlertRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertRulesRequest) Reset() {
	*x = ListAlertRulesRequest{}
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertRulesRequest) ProtoMessage() {}

func (x *ListAlertRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertRulesRequest.ProtoReflect.Descriptor instead.
func (*ListAlertRulesRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_alerting_proto_rawDescGZIP(), []int{3}
}

type ListAlertRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*AlertRuleView       `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertRulesResponse) Reset() {
	*x = ListAlertRulesResponse{}
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertRulesResponse) ProtoMessage() {}

func (x *ListAlertRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertRulesResponse.ProtoReflect.Descriptor instead.
func (*ListAlertRulesResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_alerting_proto_rawDescGZIP(), []int{4}
}

func (x *ListAlertRulesResponse) GetRules() []*AlertRuleView {
	if x != nil {
		return x.Rules
	}
	return nil
}

type UpdateAlertRuleRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Expr               *string                `protobuf:"bytes,3,opt,name=expr,proto3,oneof" json:"expr,omitempty"`
	ForDurationSeconds *int64                 `protobuf:"varint,4,opt,name=for_duration_seconds,json=forDurationSeconds,proto3,oneof" json:"for_duration_seconds,omitempty"`
	// 非 null = 整体替换（null = 不变）。
	Labels map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 非空 = 整体替换（全量替换语义用空集表达需经 Delete+Create——与
	// notifications patterns 更新同口径）。
	Channels      []string `protobuf:"bytes,6,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlertRuleRequest) Reset() {
	*x = UpdateAlertRuleRequest{}
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlertRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlertRuleRequest) ProtoMessage() {}

func (x *UpdateAlertRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlertRuleRequest.ProtoReflect.Descriptor instead.
func (*UpdateAlertRuleRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_alerting_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAlertRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAlertRuleRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateAlertRuleRequest) GetExpr() string {
	if x != nil && x.Expr != nil {
		return *x.Expr
	}
	return ""
}

func (x *UpdateAlertRuleRequest) GetForDurationSeconds() int64 {
	if x != nil && x.ForDurationSeconds != nil {
		return *x.ForDurationSeconds
	}
	return 0
}

func (x *UpdateAlertRuleRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *UpdateAlertRuleRequest) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

type UpdateAlertRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *AlertRuleView         `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlertRuleResponse) Reset() {
	*x = UpdateAlertRuleResponse{}
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlertRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlertRuleResponse) ProtoMessage() {}

func (x *UpdateAlertRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlertRuleResponse.ProtoReflect.Descriptor instead.
func (*UpdateAlertRuleResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_alerting_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAlertRuleResponse) GetRule() *AlertRuleView {
	if x != nil {
		return x.Rule
	}
	return nil
}

type DeleteAlertRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlertRuleRequest) Reset() {
	*x = DeleteAlertRuleRequest{}
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlertRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlertRuleRequest) ProtoMessage() {}

func (x *DeleteAlertRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlertRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteAlertRuleRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_alerting_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAlertRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAlertRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlertRuleResponse) Reset() {
	*x = DeleteAlertRuleResponse{}
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlertRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlertRuleResponse) ProtoMessage() {}

func (x *DeleteAlertRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlertRuleResponse.ProtoReflect.Descriptor instead.
func (*DeleteAlertRuleResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_alerting_proto_rawDescGZIP(), []int{8}
}

type SetAlertsModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAlertsModeRequest) Reset() {
	*x = SetAlertsModeRequest{}
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAlertsModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAlertsModeRequest) ProtoMessage() {}

func (x *SetAlertsModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAlertsModeRequest.ProtoReflect.Descriptor instead.
func (*SetAlertsModeRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_alerting_proto_rawDescGZIP(), []int{9}
}

func (x *SetAlertsModeRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type SetAlertsModeResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Status        *GetAlertsStatusResponse `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAlertsModeResponse) Reset() {
	*x = SetAlertsModeResponse{}
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAlertsModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAlertsModeResponse) ProtoMessage() {}

func (x *SetAlertsModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAlertsModeResponse.ProtoReflect.Descriptor instead.
func (*SetAlertsModeResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_alerting_proto_rawDescGZIP(), []int{10}
}

func (x *SetAlertsModeResponse) GetStatus() *GetAlertsStatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetAlertsStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertsStatusRequest) Reset() {
	*x = GetAlertsStatusRequest{}
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertsStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertsStatusRequest) ProtoMessage() {}

func (x *GetAlertsStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertsStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAlertsStatusRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_alerting_proto_rawDescGZIP(), []int{11}
}

type GetAlertsStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 生效模式：unset | on（缺省 unset；set 区分「缺省生效」）。
	Mode    string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	ModeSet bool   `protobuf:"varint,2,opt,name=mode_set,json=modeSet,proto3" json:"mode_set,omitempty"`
	// vmalert 服务部署态（mode=on 且 exists=false = duty 收敛中——过渡态）。
	VmalertExists bool   `protobuf:"varint,3,opt,name=vmalert_exists,json=vmalertExists,proto3" json:"vmalert_exists,omitempty"`
	VmalertImage  string `protobuf:"bytes,4,opt,name=vmalert_image,json=vmalertImage,proto3" json:"vmalert_image,omitempty"`
	// 平台规则数。
	RuleCount int32 `protobuf:"varint,5,opt,name=rule_count,json=ruleCount,proto3" json:"rule_count,omitempty"`
	// metrics.mode 当前值（前置门的可见面——alerts on 而 metrics off =
	// vmalert 被移除的休眠形态，如实并列让消费方自判）。
	MetricsMode   string `protobuf:"bytes,6,opt,name=metrics_mode,json=metricsMode,proto3" json:"metrics_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertsStatusResponse) Reset() {
	*x = GetAlertsStatusResponse{}
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertsStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertsStatusResponse) ProtoMessage() {}

func (x *GetAlertsStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertsStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAlertsStatusResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_alerting_proto_rawDescGZIP(), []int{12}
}

func (x *GetAlertsStatusResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *GetAlertsStatusResponse) GetModeSet() bool {
	if x != nil {
		return x.ModeSet
	}
	return false
}

func (x *GetAlertsStatusResponse) GetVmalertExists() bool {
	if x != nil {
		return x.VmalertExists
	}
	return false
}

func (x *GetAlertsStatusResponse) GetVmalertImage() string {
	if x != nil {
		return x.VmalertImage
	}
	return ""
}

func (x *GetAlertsStatusResponse) GetRuleCount() int32 {
	if x != nil {
		return x.RuleCount
	}
	return 0
}

func (x *GetAlertsStatusResponse) GetMetricsMode() string {
	if x != nil {
		return x.MetricsMode
	}
	return ""
}

type TestAlertRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          string                 `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestAlertRuleRequest) Reset() {
	*x = TestAlertRuleRequest{}
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestAlertRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAlertRuleRequest) ProtoMessage() {}

func (x *TestAlertRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAlertRuleRequest.ProtoReflect.Descriptor instead.
func (*TestAlertRuleRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_alerting_proto_rawDescGZIP(), []int{13}
}

func (x *TestAlertRuleRequest) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

// TestAlertRuleResponse 是 instant query 的样本回（序列 label 集 + 单点；
// 空集 = 表达式合法但当前无匹配序列——同样是「试跑成功」的事实）。
type TestAlertRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        []*MetricsSeries       `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestAlertRuleResponse) Reset() {
	*x = TestAlertRuleResponse{}
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestAlertRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAlertRuleResponse) ProtoMessage() {}

func (x *TestAlertRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_alerting_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAlertRuleResponse.ProtoReflect.Descriptor instead.
func (*TestAlertRuleResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_alerting_proto_rawDescGZIP(), []int{14}
}

func (x *TestAlertRuleResponse) GetSeries() []*MetricsSeries {
	if x != nil {
		return x.Series
	}
	return nil
}

var File_fleetly_server_v1_alerting_proto protoreflect.FileDescriptor

const file_fleetly_server_v1_alerting_proto_rawDesc = "" +
	"\n" +
	" fleetly/server/v1/alerting.proto\x12\x11fleetly.server.v1\x1a\x1bbuf/validate/validate.proto\x1a(fleetly/annotations/v1/annotations.proto\x1a\x1ffleetly/server/v1/metrics.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x8c\x03\n" +
	"\rAlertRuleView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04expr\x18\x03 \x01(\tR\x04expr\x120\n" +
	"\x14for_duration_seconds\x18\x04 \x01(\x03R\x12forDurationSeconds\x12D\n" +
	"\x06labels\x18\x05 \x03(\v2,.fleetly.server.v1.AlertRuleView.LabelsEntryR\x06labels\x12\x1a\n" +
	"\bchannels\x18\x06 \x03(\tR\bchannels\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd7\x02\n" +
	"\x16CreateAlertRuleRequest\x12<\n" +
	"\x04name\x18\x01 \x01(\tB(\xbaH%r#2!^[a-zA-Z0-9][a-zA-Z0-9._-]{0,63}$R\x04name\x12\x1e\n" +
	"\x04expr\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x10R\x04expr\x129\n" +
	"\x14for_duration_seconds\x18\x03 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\x12forDurationSeconds\x12M\n" +
	"\x06labels\x18\x04 \x03(\v25.fleetly.server.v1.CreateAlertRuleRequest.LabelsEntryR\x06labels\x12\x1a\n" +
	"\bchannels\x18\x05 \x03(\tR\bchannels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\x17CreateAlertRuleResponse\x124\n" +
	"\x04rule\x18\x01 \x01(\v2 .fleetly.server.v1.AlertRuleViewR\x04rule\"\x17\n" +
	"\x15ListAlertRulesRequest\"P\n" +
	"\x16ListAlertRulesResponse\x126\n" +
	"\x05rules\x18\x01 \x03(\v2 .fleetly.server.v1.AlertRuleViewR\x05rules\"\xaa\x03\n" +
	"\x16UpdateAlertRuleRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x12A\n" +
	"\x04name\x18\x02 \x01(\tB(\xbaH%r#2!^[a-zA-Z0-9][a-zA-Z0-9._-]{0,63}$H\x00R\x04name\x88\x01\x01\x12#\n" +
	"\x04expr\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x10H\x01R\x04expr\x88\x01\x01\x12>\n" +
	"\x14for_duration_seconds\x18\x04 \x01(\x03B\a\xbaH\x04\"\x02(\x00H\x02R\x12forDurationSeconds\x88\x01\x01\x12M\n" +
	"\x06labels\x18\x05 \x03(\v25.fleetly.server.v1.UpdateAlertRuleRequest.LabelsEntryR\x06labels\x12\x1a\n" +
	"\bchannels\x18\x06 \x03(\tR\bchannels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_nameB\a\n" +
	"\x05_exprB\x17\n" +
	"\x15_for_duration_seconds\"O\n" +
	"\x17UpdateAlertRuleResponse\x124\n" +
	"\x04rule\x18\x01 \x01(\v2 .fleetly.server.v1.AlertRuleViewR\x04rule\"1\n" +
	"\x16DeleteAlertRuleRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"\x19\n" +
	"\x17DeleteAlertRuleResponse\"<\n" +
	"\x14SetAlertsModeRequest\x12$\n" +
	"\x04mode\x18\x01 \x01(\tB\x10\xbaH\rr\vR\x05unsetR\x02onR\x04mode\"[\n" +
	"\x15SetAlertsModeResponse\x12B\n" +
	"\x06status\x18\x01 \x01(\v2*.fleetly.server.v1.GetAlertsStatusResponseR\x06status\"\x18\n" +
	"\x16GetAlertsStatusRequest\"\xd6\x01\n" +
	"\x17GetAlertsStatusResponse\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x19\n" +
	"\bmode_set\x18\x02 \x01(\bR\amodeSet\x12%\n" +
	"\x0evmalert_exists\x18\x03 \x01(\bR\rvmalertExists\x12#\n" +
	"\rvmalert_image\x18\x04 \x01(\tR\fvmalertImage\x12\x1d\n" +
	"\n" +
	"rule_count\x18\x05 \x01(\x05R\truleCount\x12!\n" +
	"\fmetrics_mode\x18\x06 \x01(\tR\vmetricsMode\"6\n" +
	"\x14TestAlertRuleRequest\x12\x1e\n" +
	"\x04expr\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x10R\x04expr\"Q\n" +
	"\x15TestAlertRuleResponse\x128\n" +
	"\x06series\x18\x01 \x03(\v2 .fleetly.server.v1.MetricsSeriesR\x06series2\x8c\b\n" +
	"\x0fAlertingService\x12\x90\x01\n" +
	"\x0fCreateAlertRule\x12).fleetly.server.v1.CreateAlertRuleRequest\x1a*.fleetly.server.v1.CreateAlertRuleResponse\"&\x82\xb5\x18\x05admin\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/alerting/rules\x12\x89\x01\n" +
	"\x0eListAlertRules\x12(.fleetly.server.v1.ListAlertRulesRequest\x1a).fleetly.server.v1.ListAlertRulesResponse\"\"\x82\xb5\x18\x04read\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/alerting/rules\x12\x95\x01\n" +
	"\x0fUpdateAlertRule\x12).fleetly.server.v1.UpdateAlertRuleRequest\x1a*.fleetly.server.v1.UpdateAlertRuleResponse\"+\x82\xb5\x18\x05admin\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/v1/alerting/rules/{id}\x12\x92\x01\n" +
	"\x0fDeleteAlertRule\x12).fleetly.server.v1.DeleteAlertRuleRequest\x1a*.fleetly.server.v1.DeleteAlertRuleResponse\"(\x82\xb5\x18\x05admin\x82\xd3\xe4\x93\x02\x19*\x17/v1/alerting/rules/{id}\x12\x8a\x01\n" +
	"\rSetAlertsMode\x12'.fleetly.server.v1.SetAlertsModeRequest\x1a(.fleetly.server.v1.SetAlertsModeResponse\"&\x82\xb5\x18\x06deploy\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/v1/alerting/mode\x12\x8d\x01\n" +
	"\x0fGetAlertsStatus\x12).fleetly.server.v1.GetAlertsStatusRequest\x1a*.fleetly.server.v1.GetAlertsStatusResponse\"#\x82\xb5\x18\x04read\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/alerting/status\x12\x8f\x01\n" +
	"\rTestAlertRule\x12'.fleetly.server.v1.TestAlertRuleRequest\x1a(.fleetly.server.v1.TestAlertRuleResponse\"+\x82\xb5\x18\x05admin\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/alerting/rules:testB\x98\x01\x92ARRP\n" +
	"\adefault\x12E\n" +
	"\x1dAn unexpected error response.\x12$\n" +
	"\"\x1a .fleetly.shared.v1.ErrorResponseZAgithub.com/fleetlyrun/fleetly/genproto/fleetly/server/v1;serverv1b\x06proto3"

var (
	file_fleetly_server_v1_alerting_proto_rawDescOnce sync.Once
	file_fleetly_server_v1_alerting_proto_rawDescData []byte
)

func file_fleetly_server_v1_alerting_proto_rawDescGZIP() []byte {
	file_fleetly_server_v1_alerting_proto_rawDescOnce.Do(func() {
		file_fleetly_server_v1_alerting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleetly_server_v1_alerting_proto_rawDesc), len(file_fleetly_server_v1_alerting_proto_rawDesc)))
	})
	return file_fleetly_server_v1_alerting_proto_rawDescData
}

var file_fleetly_server_v1_alerting_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_fleetly_server_v1_alerting_proto_goTypes = []any{
	(*AlertRuleView)(nil),           // 0: fleetly.server.v1.AlertRuleView
	(*CreateAlertRuleRequest)(nil),  // 1: fleetly.server.v1.CreateAlertRuleRequest
	(*CreateAlertRuleResponse)(nil), // 2: fleetly.server.v1.CreateAlertRuleResponse
	(*ListAlertRulesRequest)(nil),   // 3: fleetly.server.v1.ListAlertRulesRequest
	(*ListAlertRulesResponse)(nil),  // 4: fleetly.server.v1.ListAlertRulesResponse
	(*UpdateAlertRuleRequest)(nil),  // 5: fleetly.server.v1.UpdateAlertRuleRequest
	(*UpdateAlertRuleResponse)(nil), // 6: fleetly.server.v1.UpdateAlertRuleResponse
	(*DeleteAlertRuleRequest)(nil),  // 7: fleetly.server.v1.DeleteAlertRuleRequest
	(*DeleteAlertRuleResponse)(nil), // 8: fleetly.server.v1.DeleteAlertRuleResponse
	(*SetAlertsModeRequest)(nil),    // 9: fleetly.server.v1.SetAlertsModeRequest
	(*SetAlertsModeResponse)(nil),   // 10: fleetly.server.v1.SetAlertsModeResponse
	(*GetAlertsStatusRequest)(nil),  // 11: fleetly.server.v1.GetAlertsStatusRequest
	(*GetAlertsStatusResponse)(nil), // 12: fleetly.server.v1.GetAlertsStatusResponse
	(*TestAlertRuleRequest)(nil),    // 13: fleetly.server.v1.TestAlertRuleRequest
	(*TestAlertRuleResponse)(nil),   // 14: fleetly.server.v1.TestAlertRuleResponse
	nil,                             // 15: fleetly.server.v1.AlertRuleView.LabelsEntry
	nil,                             // 16: fleetly.server.v1.CreateAlertRuleRequest.LabelsEntry
	nil,                             // 17: fleetly.server.v1.UpdateAlertRuleRequest.LabelsEntry
	(*timestamppb.Timestamp)(nil),   // 18: google.protobuf.Timestamp
	(*MetricsSeries)(nil),           // 19: fleetly.server.v1.MetricsSeries
}
var file_fleetly_server_v1_alerting_proto_depIdxs = []int32{
	15, // 0: fleetly.server.v1.AlertRuleView.labels:type_name -> fleetly.server.v1.AlertRuleView.LabelsEntry
	18, // 1: fleetly.server.v1.AlertRuleView.created_at:type_name -> google.protobuf.Timestamp
	18, // 2: fleetly.server.v1.AlertRuleView.updated_at:type_name -> google.protobuf.Timestamp
	16, // 3: fleetly.server.v1.CreateAlertRuleRequest.labels:type_name -> fleetly.server.v1.CreateAlertRuleRequest.LabelsEntry
	0,  // 4: fleetly.server.v1.CreateAlertRuleResponse.rule:type_name -> fleetly.server.v1.AlertRuleView
	0,  // 5: fleetly.server.v1.ListAlertRulesResponse.rules:type_name -> fleetly.server.v1.AlertRuleView
	17, // 6: fleetly.server.v1.UpdateAlertRuleRequest.labels:type_name -> fleetly.server.v1.UpdateAlertRuleRequest.LabelsEntry
	0,  // 7: fleetly.server.v1.UpdateAlertRuleResponse.rule:type_name -> fleetly.server.v1.AlertRuleView
	12, // 8: fleetly.server.v1.SetAlertsModeResponse.status:type_name -> fleetly.server.v1.GetAlertsStatusResponse
	19, // 9: fleetly.server.v1.TestAlertRuleResponse.series:type_name -> fleetly.server.v1.MetricsSeries
	1,  // 10: fleetly.server.v1.AlertingService.CreateAlertRule:input_type -> fleetly.server.v1.CreateAlertRuleRequest
	3,  // 11: fleetly.server.v1.AlertingService.ListAlertRules:input_type -> fleetly.server.v1.ListAlertRulesRequest
	5,  // 12: fleetly.server.v1.AlertingService.UpdateAlertRule:input_type -> fleetly.server.v1.UpdateAlertRuleRequest
	7,  // 13: fleetly.server.v1.AlertingService.DeleteAlertRule:input_type -> fleetly.server.v1.DeleteAlertRuleRequest
	9,  // 14: fleetly.server.v1.AlertingService.SetAlertsMode:input_type -> fleetly.server.v1.SetAlertsModeRequest
	11, // 15: fleetly.server.v1.AlertingService.GetAlertsStatus:input_type -> fleetly.server.v1.GetAlertsStatusRequest
	13, // 16: fleetly.server.v1.AlertingService.TestAlertRule:input_type -> fleetly.server.v1.TestAlertRuleRequest
	2,  // 17: fleetly.server.v1.AlertingService.CreateAlertRule:output_type -> fleetly.server.v1.CreateAlertRuleResponse
	4,  // 18: fleetly.server.v1.AlertingService.ListAlertRules:output_type -> fleetly.server.v1.ListAlertRulesResponse
	6,  // 19: fleetly.server.v1.AlertingService.UpdateAlertRule:output_type -> fleetly.server.v1.UpdateAlertRuleResponse
	8,  // 20: fleetly.server.v1.AlertingService.DeleteAlertRule:output_type -> fleetly.server.v1.DeleteAlertRuleResponse
	10, // 21: fleetly.server.v1.AlertingService.SetAlertsMode:output_type -> fleetly.server.v1.SetAlertsModeResponse
	12, // 22: fleetly.server.v1.AlertingService.GetAlertsStatus:output_type -> fleetly.server.v1.GetAlertsStatusResponse
	14, // 23: fleetly.server.v1.AlertingService.TestAlertRule:output_type -> fleetly.server.v1.TestAlertRuleResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_fleetly_server_v1_alerting_proto_init() }
func file_fleetly_server_v1_alerting_proto_init() {
	if File_fleetly_server_v1_alerting_proto != nil {
		return
	}
	file_fleetly_server_v1_metrics_proto_init()
	file_fleetly_server_v1_alerting_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleetly_server_v1_alerting_proto_rawDesc), len(file_fleetly_server_v1_alerting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleetly_server_v1_alerting_proto_goTypes,
		DependencyIndexes: file_fleetly_server_v1_alerting_proto_depIdxs,
		MessageInfos:      file_fleetly_server_v1_alerting_proto_msgTypes,
	}.Build()
	File_fleetly_server_v1_alerting_proto = out.File
	file_fleetly_server_v1_alerting_proto_goTypes = nil
	file_fleetly_server_v1_alerting_proto_depIdxs = nil
}
