// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: fleetly/server/v1/cron.proto

package serverv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/fleetlyrun/fleetly/genproto/fleetly/annotations/v1"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TriggerCronRunRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 应用名（compose 应用名）。
	App string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	// compose 服务名（必须声明 fleetly.cron，否则 404 语义）。
	Service       string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerCronRunRequest) Reset() {
	*x = TriggerCronRunRequest{}
	mi := &file_fleetly_server_v1_cron_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerCronRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerCronRunRequest) ProtoMessage() {}

func (x *TriggerCronRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_cron_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerCronRunRequest.ProtoReflect.Descriptor instead.
func (*TriggerCronRunRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_cron_proto_rawDescGZIP(), []int{0}
}

func (x *TriggerCronRunRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *TriggerCronRunRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type TriggerCronRunResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 触发结果行（status=started 或 skipped；与到点触发同构）。
	Run           *CronRunView `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerCronRunResponse) Reset() {
	*x = TriggerCronRunResponse{}
	mi := &file_fleetly_server_v1_cron_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerCronRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerCronRunResponse) ProtoMessage() {}

func (x *TriggerCronRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_cron_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerCronRunResponse.ProtoReflect.Descriptor instead.
func (*TriggerCronRunResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_cron_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerCronRunResponse) GetRun() *CronRunView {
	if x != nil {
		return x.Run
	}
	return nil
}

type ListCronRunsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	App   string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	// 收窄到单 schedule（空 = 全部）。
	Service string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	// 行数上限（缺省 20；≤20 的量级面，无分页游标）。
	Limit         int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCronRunsRequest) Reset() {
	*x = ListCronRunsRequest{}
	mi := &file_fleetly_server_v1_cron_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCronRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCronRunsRequest) ProtoMessage() {}

func (x *ListCronRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_cron_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCronRunsRequest.ProtoReflect.Descriptor instead.
func (*ListCronRunsRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_cron_proto_rawDescGZIP(), []int{2}
}

func (x *ListCronRunsRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *ListCronRunsRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ListCronRunsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListCronRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Runs          []*CronRunView         `protobuf:"bytes,2,rep,name=runs,proto3" json:"runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCronRunsResponse) Reset() {
	*x = ListCronRunsResponse{}
	mi := &file_fleetly_server_v1_cron_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCronRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCronRunsResponse) ProtoMessage() {}

func (x *ListCronRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_cron_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCronRunsResponse.ProtoReflect.Descriptor instead.
func (*ListCronRunsResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_cron_proto_rawDescGZIP(), []int{3}
}

func (x *ListCronRunsResponse) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *ListCronRunsResponse) GetRuns() []*CronRunView {
	if x != nil {
		return x.Runs
	}
	return nil
}

// CronRunView 是一次 cron 触发的台账投影（状态词表 started | succeeded |
// failed | timeout | skipped；skipped 行带 skip_reason：
// overlap | node_unavailable | missed_downtime | interrupted）。
type CronRunView struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Service    string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Expression string                 `protobuf:"bytes,3,opt,name=expression,proto3" json:"expression,omitempty"`
	// 命中的 cron 点（手动触发 = 触发时刻）。
	ScheduledAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	// job 启动时刻（skipped 行不输出）。
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// 终态收口时刻（在途/skipped 行不输出）。
	FinishedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Status     string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	SkipReason string                 `protobuf:"bytes,8,opt,name=skip_reason,json=skipReason,proto3" json:"skip_reason,omitempty"`
	// 一次性 job 服务名（skipped 行不输出）。
	JobService string `protobuf:"bytes,9,opt,name=job_service,json=jobService,proto3" json:"job_service,omitempty"`
	// 失败/超时原因摘要。
	Error         string `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronRunView) Reset() {
	*x = CronRunView{}
	mi := &file_fleetly_server_v1_cron_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronRunView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronRunView) ProtoMessage() {}

func (x *CronRunView) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_cron_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronRunView.ProtoReflect.Descriptor instead.
func (*CronRunView) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_cron_proto_rawDescGZIP(), []int{4}
}

func (x *CronRunView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CronRunView) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *CronRunView) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *CronRunView) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *CronRunView) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *CronRunView) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *CronRunView) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CronRunView) GetSkipReason() string {
	if x != nil {
		return x.SkipReason
	}
	return ""
}

func (x *CronRunView) GetJobService() string {
	if x != nil {
		return x.JobService
	}
	return ""
}

func (x *CronRunView) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_fleetly_server_v1_cron_proto protoreflect.FileDescriptor

const file_fleetly_server_v1_cron_proto_rawDesc = "" +
	"\n" +
	"\x1cfleetly/server/v1/cron.proto\x12\x11fleetly.server.v1\x1a\x1bbuf/validate/validate.proto\x1a(fleetly/annotations/v1/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"U\n" +
	"\x15TriggerCronRunRequest\x12\x19\n" +
	"\x03app\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03app\x12!\n" +
	"\aservice\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\aservice\"J\n" +
	"\x16TriggerCronRunResponse\x120\n" +
	"\x03run\x18\x01 \x01(\v2\x1e.fleetly.server.v1.CronRunViewR\x03run\"k\n" +
	"\x13ListCronRunsRequest\x12\x19\n" +
	"\x03app\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03app\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1f\n" +
	"\x05limit\x18\x03 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x00R\x05limit\"\\\n" +
	"\x14ListCronRunsResponse\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x122\n" +
	"\x04runs\x18\x02 \x03(\v2\x1e.fleetly.server.v1.CronRunViewR\x04runs\"\xfe\x02\n" +
	"\vCronRunView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1e\n" +
	"\n" +
	"expression\x18\x03 \x01(\tR\n" +
	"expression\x12=\n" +
	"\fscheduled_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1f\n" +
	"\vskip_reason\x18\b \x01(\tR\n" +
	"skipReason\x12\x1f\n" +
	"\vjob_service\x18\t \x01(\tR\n" +
	"jobService\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error2\xc1\x02\n" +
	"\vCronService\x12\xa5\x01\n" +
	"\x0eTriggerCronRun\x12(.fleetly.server.v1.TriggerCronRunRequest\x1a).fleetly.server.v1.TriggerCronRunResponse\">\x82\xb5\x18\x06deploy\x82\xd3\xe4\x93\x02.:\x01*\")/v1/apps/{app}/services/{service}/trigger\x12\x89\x01\n" +
	"\fListCronRuns\x12&.fleetly.server.v1.ListCronRunsRequest\x1a'.fleetly.server.v1.ListCronRunsResponse\"(\x82\xb5\x18\x04read\x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/apps/{app}/cron-runsB\x98\x01\x92ARRP\n" +
	"\adefault\x12E\n" +
	"\x1dAn unexpected error response.\x12$\n" +
	"\"\x1a .fleetly.shared.v1.ErrorResponseZAgithub.com/fleetlyrun/fleetly/genproto/fleetly/server/v1;serverv1b\x06proto3"

var (
	file_fleetly_server_v1_cron_proto_rawDescOnce sync.Once
	file_fleetly_server_v1_cron_proto_rawDescData []byte
)

func file_fleetly_server_v1_cron_proto_rawDescGZIP() []byte {
	file_fleetly_server_v1_cron_proto_rawDescOnce.Do(func() {
		file_fleetly_server_v1_cron_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleetly_server_v1_cron_proto_rawDesc), len(file_fleetly_server_v1_cron_proto_rawDesc)))
	})
	return file_fleetly_server_v1_cron_proto_rawDescData
}

var file_fleetly_server_v1_cron_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_fleetly_server_v1_cron_proto_goTypes = []any{
	(*TriggerCronRunRequest)(nil),  // 0: fleetly.server.v1.TriggerCronRunRequest
	(*TriggerCronRunResponse)(nil), // 1: fleetly.server.v1.TriggerCronRunResponse
	(*ListCronRunsRequest)(nil),    // 2: fleetly.server.v1.ListCronRunsRequest
	(*ListCronRunsResponse)(nil),   // 3: fleetly.server.v1.ListCronRunsResponse
	(*CronRunView)(nil),            // 4: fleetly.server.v1.CronRunView
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
}
var file_fleetly_server_v1_cron_proto_depIdxs = []int32{
	4, // 0: fleetly.server.v1.TriggerCronRunResponse.run:type_name -> fleetly.server.v1.CronRunView
	4, // 1: fleetly.server.v1.ListCronRunsResponse.runs:type_name -> fleetly.server.v1.CronRunView
	5, // 2: fleetly.server.v1.CronRunView.scheduled_at:type_name -> google.protobuf.Timestamp
	5, // 3: fleetly.server.v1.CronRunView.started_at:type_name -> google.protobuf.Timestamp
	5, // 4: fleetly.server.v1.CronRunView.finished_at:type_name -> google.protobuf.Timestamp
	0, // 5: fleetly.server.v1.CronService.TriggerCronRun:input_type -> fleetly.server.v1.TriggerCronRunRequest
	2, // 6: fleetly.server.v1.CronService.ListCronRuns:input_type -> fleetly.server.v1.ListCronRunsRequest
	1, // 7: fleetly.server.v1.CronService.TriggerCronRun:output_type -> fleetly.server.v1.TriggerCronRunResponse
	3, // 8: fleetly.server.v1.CronService.ListCronRuns:output_type -> fleetly.server.v1.ListCronRunsResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_fleetly_server_v1_cron_proto_init() }
func file_fleetly_server_v1_cron_proto_init() {
	if File_fleetly_server_v1_cron_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleetly_server_v1_cron_proto_rawDesc), len(file_fleetly_server_v1_cron_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleetly_server_v1_cron_proto_goTypes,
		DependencyIndexes: file_fleetly_server_v1_cron_proto_depIdxs,
		MessageInfos:      file_fleetly_server_v1_cron_proto_msgTypes,
	}.Build()
	File_fleetly_server_v1_cron_proto = out.File
	file_fleetly_server_v1_cron_proto_goTypes = nil
	file_fleetly_server_v1_cron_proto_depIdxs = nil
}
