// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: fleetly/server/v1/database.proto

package serverv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DatabaseService_CreateDatabase_FullMethodName            = "/fleetly.server.v1.DatabaseService/CreateDatabase"
	DatabaseService_GetDatabase_FullMethodName               = "/fleetly.server.v1.DatabaseService/GetDatabase"
	DatabaseService_ListDatabases_FullMethodName             = "/fleetly.server.v1.DatabaseService/ListDatabases"
	DatabaseService_DeleteDatabase_FullMethodName            = "/fleetly.server.v1.DatabaseService/DeleteDatabase"
	DatabaseService_SuspendDatabase_FullMethodName           = "/fleetly.server.v1.DatabaseService/SuspendDatabase"
	DatabaseService_ResumeDatabase_FullMethodName            = "/fleetly.server.v1.DatabaseService/ResumeDatabase"
	DatabaseService_RetryDatabase_FullMethodName             = "/fleetly.server.v1.DatabaseService/RetryDatabase"
	DatabaseService_UpdateDatabaseSettings_FullMethodName    = "/fleetly.server.v1.DatabaseService/UpdateDatabaseSettings"
	DatabaseService_RotateDatabaseCredentials_FullMethodName = "/fleetly.server.v1.DatabaseService/RotateDatabaseCredentials"
	DatabaseService_RevealDatabaseCredentials_FullMethodName = "/fleetly.server.v1.DatabaseService/RevealDatabaseCredentials"
	DatabaseService_TriggerDatabaseBackup_FullMethodName     = "/fleetly.server.v1.DatabaseService/TriggerDatabaseBackup"
	DatabaseService_ListDatabaseBackups_FullMethodName       = "/fleetly.server.v1.DatabaseService/ListDatabaseBackups"
	DatabaseService_RestoreDatabaseBackup_FullMethodName     = "/fleetly.server.v1.DatabaseService/RestoreDatabaseBackup"
	DatabaseService_UpgradeDatabase_FullMethodName           = "/fleetly.server.v1.DatabaseService/UpgradeDatabase"
)

// DatabaseServiceClient is the client API for DatabaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DatabaseService 是库实例资源面（E4 数据库托管，managed-databases §5.1
// 契约加法的 S2 子集：生命周期生命周期 7 RPC——create/get/list/delete/
// suspend/resume/retry/settings）。独立成 service 的理由与 CronService 同
// 型：库实例是独立一等资源（D-DB-1 用户终裁）——自有表、自有生命周期状
// 态机、不复用 apps 部署管线；并入 AppsService 会把两个领域混进一个资源面。
//
// S4/S5 域的 RPC（UpgradeDatabase/RotateDatabaseCredentials/
// TriggerDatabaseBackup/ListDatabaseBackups/RestoreDatabaseBackup）随各自
// 票据追加——本文件只加法，零 breaking。
//
// 错误语义（managed-databases §5.2，D-DB-8 零新增码）：
//
//	E_DB_NOT_FOUND            404（目标不存在或已进入 deleting/deleted）
//	E_DB_REFERENCED           409（有引用 app 禁删，context 带引用清单）
//	E_DB_TEMPLATE_UNSUPPORTED 400（模板 ID 未知 / 设置违反受管面）
//	E_STATE_VERSION_CONFLICT  409（前置态/CAS 冲突——context 带
//	                            current_state 与合法前置态清单）
type DatabaseServiceClient interface {
	// CreateDatabase 创建库实例（受理即 provisioning——无 created 态；凭据
	// 生成一次、age 密文落库；收敛器异步建现场过健康门 → ready）。
	CreateDatabase(ctx context.Context, in *CreateDatabaseRequest, opts ...grpc.CallOption) (*CreateDatabaseResponse, error)
	// GetDatabase 库实例详情（连接信息脱敏投影——密码明文零离开存储；显式
	// reveal 面随 S4/S6 轮换与 Console 票据）。
	GetDatabase(ctx context.Context, in *GetDatabaseRequest, opts ...grpc.CallOption) (*GetDatabaseResponse, error)
	// ListDatabases 库实例列表（name 字典序；deleted tombstone 不进默认列表
	// ——与 apps 列表同口径）。
	ListDatabases(ctx context.Context, in *ListDatabasesRequest, opts ...grpc.CallOption) (*ListDatabasesResponse, error)
	// DeleteDatabase 删除受理（引用守卫通过后 → deleting tombstone 第一拍；
	// reap 收敛步幂等清理受管对象。confirm = 实例名——数据安全两段式确认；
	// delete_volumes 默认 false = 卷保留转 orphaned，true = 删数据卷不可逆）。
	DeleteDatabase(ctx context.Context, in *DeleteDatabaseRequest, opts ...grpc.CallOption) (*DeleteDatabaseResponse, error)
	// SuspendDatabase 暂停（scale 0 保留服务与卷；引用方连不上是诚实暴露）。
	SuspendDatabase(ctx context.Context, in *SuspendDatabaseRequest, opts ...grpc.CallOption) (*SuspendDatabaseResponse, error)
	// ResumeDatabase 恢复（paused → provisioning 重收敛 → ready/degraded）。
	ResumeDatabase(ctx context.Context, in *ResumeDatabaseRequest, opts ...grpc.CallOption) (*ResumeDatabaseResponse, error)
	// RetryDatabase 显式重试（failed → provisioning 重收敛；现场保留语义下
	// 失败的唯一出边）。
	RetryDatabase(ctx context.Context, in *RetryDatabaseRequest, opts ...grpc.CallOption) (*RetryDatabaseResponse, error)
	// UpdateDatabaseSettings 设置变更（限额 + 备份计划；任意非终态准入、主
	// 状态不变；限额变更 = spec 重建由收敛器在下一拍承载）。镜像/引擎参数
	// 受管（违规模板字段不存在于请求——E_DB_TEMPLATE_UNSUPPORTED 面）。
	UpdateDatabaseSettings(ctx context.Context, in *UpdateDatabaseSettingsRequest, opts ...grpc.CallOption) (*UpdateDatabaseSettingsResponse, error)
	// RotateDatabaseCredentials 凭据轮换（E4 managed-databases §2.5，S4）：
	// 破坏性两段式（confirm = 实例名）。合法前置态 ready/degraded/paused
	// （§2.3 操作表；PG 暂停期拒绝——postgres 需运行中实例才能 ALTER USER，
	// 如实报 409 并提示先 resume）。引擎侧成功后：引用方 system 物化行回
	// pending + 平台自动触发全部引用 app 重部署（各自走正常部署队列）。
	RotateDatabaseCredentials(ctx context.Context, in *RotateDatabaseCredentialsRequest, opts ...grpc.CallOption) (*RotateDatabaseCredentialsResponse, error)
	// RevealDatabaseCredentials 连接信息显式展开（admin scope；§2.5「Console
	// 库详情页展示连接信息，密码默认脱敏、显式展开」的 API 面——含密码明文
	// 与完整 URL；审计 db.reveal 承载敏感访问留痕，不产生事件）。
	RevealDatabaseCredentials(ctx context.Context, in *RevealDatabaseCredentialsRequest, opts ...grpc.CallOption) (*RevealDatabaseCredentialsResponse, error)
	// TriggerDatabaseBackup 手动备份受理（E4 S5，managed-databases §2.6）：
	// 异步受理（job 分钟级——响应即 accepted，结论经台账与 db.backup_* 事件
	// 披露；在途备份无台账行）。合法前置态 ready/degraded（§2.3 操作表）；
	// per 实例操作互斥（备份/恢复/升级并发第二笔 → 409）。s3.mode=unset →
	// E_S3_NOT_CONFIGURED（409——诚实拒绝，与注入前哨同码同语义）。
	TriggerDatabaseBackup(ctx context.Context, in *TriggerDatabaseBackupRequest, opts ...grpc.CallOption) (*TriggerDatabaseBackupResponse, error)
	// ListDatabaseBackups 备份台账列表（created_at 降序——恢复目标选择与
	// Console 备份列表的数据源；kind/snapshot/size/verify_status/error 全量
	// 事实面）。
	ListDatabaseBackups(ctx context.Context, in *ListDatabaseBackupsRequest, opts ...grpc.CallOption) (*ListDatabaseBackupsResponse, error)
	// RestoreDatabaseBackup 原地恢复受理（破坏性两段式 confirm + 快照归属
	// 守卫：只重放本实例台账内的快照）。停库重放：实例 scale 0 → job 挂卷
	// rw 重放 → 重部署（异步——结论经 db.restore_* 事件披露；恢复中断 =
	// 实例保持停止 + E_DB_RESTORE_FAILED 事件的 critical 口径，§2.6）。
	RestoreDatabaseBackup(ctx context.Context, in *RestoreDatabaseBackupRequest, opts ...grpc.CallOption) (*RestoreDatabaseBackupResponse, error)
	// UpgradeDatabase 受控升级受理（E4 S5，managed-databases §2.2）：①
	// pre_upgrade 备份门（verify 通过才继续——失败实例不动）②digest 换新
	// 受控重建 ③健康门 ④失败 = digest 归位 + db.upgrade_failed + 状态落
	// degraded。异步受理（备份门与健康门是分钟级）；paused = 仅换 spec 不
	// 重启（resume 时以新版本重建）。合法前置态 ready/degraded/paused。
	UpgradeDatabase(ctx context.Context, in *UpgradeDatabaseRequest, opts ...grpc.CallOption) (*UpgradeDatabaseResponse, error)
}

type databaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDatabaseServiceClient(cc grpc.ClientConnInterface) DatabaseServiceClient {
	return &databaseServiceClient{cc}
}

func (c *databaseServiceClient) CreateDatabase(ctx context.Context, in *CreateDatabaseRequest, opts ...grpc.CallOption) (*CreateDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDatabaseResponse)
	err := c.cc.Invoke(ctx, DatabaseService_CreateDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) GetDatabase(ctx context.Context, in *GetDatabaseRequest, opts ...grpc.CallOption) (*GetDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDatabaseResponse)
	err := c.cc.Invoke(ctx, DatabaseService_GetDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) ListDatabases(ctx context.Context, in *ListDatabasesRequest, opts ...grpc.CallOption) (*ListDatabasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDatabasesResponse)
	err := c.cc.Invoke(ctx, DatabaseService_ListDatabases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) DeleteDatabase(ctx context.Context, in *DeleteDatabaseRequest, opts ...grpc.CallOption) (*DeleteDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDatabaseResponse)
	err := c.cc.Invoke(ctx, DatabaseService_DeleteDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) SuspendDatabase(ctx context.Context, in *SuspendDatabaseRequest, opts ...grpc.CallOption) (*SuspendDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuspendDatabaseResponse)
	err := c.cc.Invoke(ctx, DatabaseService_SuspendDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) ResumeDatabase(ctx context.Context, in *ResumeDatabaseRequest, opts ...grpc.CallOption) (*ResumeDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeDatabaseResponse)
	err := c.cc.Invoke(ctx, DatabaseService_ResumeDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) RetryDatabase(ctx context.Context, in *RetryDatabaseRequest, opts ...grpc.CallOption) (*RetryDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryDatabaseResponse)
	err := c.cc.Invoke(ctx, DatabaseService_RetryDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) UpdateDatabaseSettings(ctx context.Context, in *UpdateDatabaseSettingsRequest, opts ...grpc.CallOption) (*UpdateDatabaseSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDatabaseSettingsResponse)
	err := c.cc.Invoke(ctx, DatabaseService_UpdateDatabaseSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) RotateDatabaseCredentials(ctx context.Context, in *RotateDatabaseCredentialsRequest, opts ...grpc.CallOption) (*RotateDatabaseCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateDatabaseCredentialsResponse)
	err := c.cc.Invoke(ctx, DatabaseService_RotateDatabaseCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) RevealDatabaseCredentials(ctx context.Context, in *RevealDatabaseCredentialsRequest, opts ...grpc.CallOption) (*RevealDatabaseCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevealDatabaseCredentialsResponse)
	err := c.cc.Invoke(ctx, DatabaseService_RevealDatabaseCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) TriggerDatabaseBackup(ctx context.Context, in *TriggerDatabaseBackupRequest, opts ...grpc.CallOption) (*TriggerDatabaseBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerDatabaseBackupResponse)
	err := c.cc.Invoke(ctx, DatabaseService_TriggerDatabaseBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) ListDatabaseBackups(ctx context.Context, in *ListDatabaseBackupsRequest, opts ...grpc.CallOption) (*ListDatabaseBackupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDatabaseBackupsResponse)
	err := c.cc.Invoke(ctx, DatabaseService_ListDatabaseBackups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) RestoreDatabaseBackup(ctx context.Context, in *RestoreDatabaseBackupRequest, opts ...grpc.CallOption) (*RestoreDatabaseBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreDatabaseBackupResponse)
	err := c.cc.Invoke(ctx, DatabaseService_RestoreDatabaseBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) UpgradeDatabase(ctx context.Context, in *UpgradeDatabaseRequest, opts ...grpc.CallOption) (*UpgradeDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpgradeDatabaseResponse)
	err := c.cc.Invoke(ctx, DatabaseService_UpgradeDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatabaseServiceServer is the server API for DatabaseService service.
// All implementations must embed UnimplementedDatabaseServiceServer
// for forward compatibility.
//
// DatabaseService 是库实例资源面（E4 数据库托管，managed-databases §5.1
// 契约加法的 S2 子集：生命周期生命周期 7 RPC——create/get/list/delete/
// suspend/resume/retry/settings）。独立成 service 的理由与 CronService 同
// 型：库实例是独立一等资源（D-DB-1 用户终裁）——自有表、自有生命周期状
// 态机、不复用 apps 部署管线；并入 AppsService 会把两个领域混进一个资源面。
//
// S4/S5 域的 RPC（UpgradeDatabase/RotateDatabaseCredentials/
// TriggerDatabaseBackup/ListDatabaseBackups/RestoreDatabaseBackup）随各自
// 票据追加——本文件只加法，零 breaking。
//
// 错误语义（managed-databases §5.2，D-DB-8 零新增码）：
//
//	E_DB_NOT_FOUND            404（目标不存在或已进入 deleting/deleted）
//	E_DB_REFERENCED           409（有引用 app 禁删，context 带引用清单）
//	E_DB_TEMPLATE_UNSUPPORTED 400（模板 ID 未知 / 设置违反受管面）
//	E_STATE_VERSION_CONFLICT  409（前置态/CAS 冲突——context 带
//	                            current_state 与合法前置态清单）
type DatabaseServiceServer interface {
	// CreateDatabase 创建库实例（受理即 provisioning——无 created 态；凭据
	// 生成一次、age 密文落库；收敛器异步建现场过健康门 → ready）。
	CreateDatabase(context.Context, *CreateDatabaseRequest) (*CreateDatabaseResponse, error)
	// GetDatabase 库实例详情（连接信息脱敏投影——密码明文零离开存储；显式
	// reveal 面随 S4/S6 轮换与 Console 票据）。
	GetDatabase(context.Context, *GetDatabaseRequest) (*GetDatabaseResponse, error)
	// ListDatabases 库实例列表（name 字典序；deleted tombstone 不进默认列表
	// ——与 apps 列表同口径）。
	ListDatabases(context.Context, *ListDatabasesRequest) (*ListDatabasesResponse, error)
	// DeleteDatabase 删除受理（引用守卫通过后 → deleting tombstone 第一拍；
	// reap 收敛步幂等清理受管对象。confirm = 实例名——数据安全两段式确认；
	// delete_volumes 默认 false = 卷保留转 orphaned，true = 删数据卷不可逆）。
	DeleteDatabase(context.Context, *DeleteDatabaseRequest) (*DeleteDatabaseResponse, error)
	// SuspendDatabase 暂停（scale 0 保留服务与卷；引用方连不上是诚实暴露）。
	SuspendDatabase(context.Context, *SuspendDatabaseRequest) (*SuspendDatabaseResponse, error)
	// ResumeDatabase 恢复（paused → provisioning 重收敛 → ready/degraded）。
	ResumeDatabase(context.Context, *ResumeDatabaseRequest) (*ResumeDatabaseResponse, error)
	// RetryDatabase 显式重试（failed → provisioning 重收敛；现场保留语义下
	// 失败的唯一出边）。
	RetryDatabase(context.Context, *RetryDatabaseRequest) (*RetryDatabaseResponse, error)
	// UpdateDatabaseSettings 设置变更（限额 + 备份计划；任意非终态准入、主
	// 状态不变；限额变更 = spec 重建由收敛器在下一拍承载）。镜像/引擎参数
	// 受管（违规模板字段不存在于请求——E_DB_TEMPLATE_UNSUPPORTED 面）。
	UpdateDatabaseSettings(context.Context, *UpdateDatabaseSettingsRequest) (*UpdateDatabaseSettingsResponse, error)
	// RotateDatabaseCredentials 凭据轮换（E4 managed-databases §2.5，S4）：
	// 破坏性两段式（confirm = 实例名）。合法前置态 ready/degraded/paused
	// （§2.3 操作表；PG 暂停期拒绝——postgres 需运行中实例才能 ALTER USER，
	// 如实报 409 并提示先 resume）。引擎侧成功后：引用方 system 物化行回
	// pending + 平台自动触发全部引用 app 重部署（各自走正常部署队列）。
	RotateDatabaseCredentials(context.Context, *RotateDatabaseCredentialsRequest) (*RotateDatabaseCredentialsResponse, error)
	// RevealDatabaseCredentials 连接信息显式展开（admin scope；§2.5「Console
	// 库详情页展示连接信息，密码默认脱敏、显式展开」的 API 面——含密码明文
	// 与完整 URL；审计 db.reveal 承载敏感访问留痕，不产生事件）。
	RevealDatabaseCredentials(context.Context, *RevealDatabaseCredentialsRequest) (*RevealDatabaseCredentialsResponse, error)
	// TriggerDatabaseBackup 手动备份受理（E4 S5，managed-databases §2.6）：
	// 异步受理（job 分钟级——响应即 accepted，结论经台账与 db.backup_* 事件
	// 披露；在途备份无台账行）。合法前置态 ready/degraded（§2.3 操作表）；
	// per 实例操作互斥（备份/恢复/升级并发第二笔 → 409）。s3.mode=unset →
	// E_S3_NOT_CONFIGURED（409——诚实拒绝，与注入前哨同码同语义）。
	TriggerDatabaseBackup(context.Context, *TriggerDatabaseBackupRequest) (*TriggerDatabaseBackupResponse, error)
	// ListDatabaseBackups 备份台账列表（created_at 降序——恢复目标选择与
	// Console 备份列表的数据源；kind/snapshot/size/verify_status/error 全量
	// 事实面）。
	ListDatabaseBackups(context.Context, *ListDatabaseBackupsRequest) (*ListDatabaseBackupsResponse, error)
	// RestoreDatabaseBackup 原地恢复受理（破坏性两段式 confirm + 快照归属
	// 守卫：只重放本实例台账内的快照）。停库重放：实例 scale 0 → job 挂卷
	// rw 重放 → 重部署（异步——结论经 db.restore_* 事件披露；恢复中断 =
	// 实例保持停止 + E_DB_RESTORE_FAILED 事件的 critical 口径，§2.6）。
	RestoreDatabaseBackup(context.Context, *RestoreDatabaseBackupRequest) (*RestoreDatabaseBackupResponse, error)
	// UpgradeDatabase 受控升级受理（E4 S5，managed-databases §2.2）：①
	// pre_upgrade 备份门（verify 通过才继续——失败实例不动）②digest 换新
	// 受控重建 ③健康门 ④失败 = digest 归位 + db.upgrade_failed + 状态落
	// degraded。异步受理（备份门与健康门是分钟级）；paused = 仅换 spec 不
	// 重启（resume 时以新版本重建）。合法前置态 ready/degraded/paused。
	UpgradeDatabase(context.Context, *UpgradeDatabaseRequest) (*UpgradeDatabaseResponse, error)
	mustEmbedUnimplementedDatabaseServiceServer()
}

// UnimplementedDatabaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatabaseServiceServer struct{}

func (UnimplementedDatabaseServiceServer) CreateDatabase(context.Context, *CreateDatabaseRequest) (*CreateDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDatabase not implemented")
}
func (UnimplementedDatabaseServiceServer) GetDatabase(context.Context, *GetDatabaseRequest) (*GetDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDatabase not implemented")
}
func (UnimplementedDatabaseServiceServer) ListDatabases(context.Context, *ListDatabasesRequest) (*ListDatabasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDatabases not implemented")
}
func (UnimplementedDatabaseServiceServer) DeleteDatabase(context.Context, *DeleteDatabaseRequest) (*DeleteDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDatabase not implemented")
}
func (UnimplementedDatabaseServiceServer) SuspendDatabase(context.Context, *SuspendDatabaseRequest) (*SuspendDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuspendDatabase not implemented")
}
func (UnimplementedDatabaseServiceServer) ResumeDatabase(context.Context, *ResumeDatabaseRequest) (*ResumeDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeDatabase not implemented")
}
func (UnimplementedDatabaseServiceServer) RetryDatabase(context.Context, *RetryDatabaseRequest) (*RetryDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryDatabase not implemented")
}
func (UnimplementedDatabaseServiceServer) UpdateDatabaseSettings(context.Context, *UpdateDatabaseSettingsRequest) (*UpdateDatabaseSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDatabaseSettings not implemented")
}
func (UnimplementedDatabaseServiceServer) RotateDatabaseCredentials(context.Context, *RotateDatabaseCredentialsRequest) (*RotateDatabaseCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateDatabaseCredentials not implemented")
}
func (UnimplementedDatabaseServiceServer) RevealDatabaseCredentials(context.Context, *RevealDatabaseCredentialsRequest) (*RevealDatabaseCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevealDatabaseCredentials not implemented")
}
func (UnimplementedDatabaseServiceServer) TriggerDatabaseBackup(context.Context, *TriggerDatabaseBackupRequest) (*TriggerDatabaseBackupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerDatabaseBackup not implemented")
}
func (UnimplementedDatabaseServiceServer) ListDatabaseBackups(context.Context, *ListDatabaseBackupsRequest) (*ListDatabaseBackupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDatabaseBackups not implemented")
}
func (UnimplementedDatabaseServiceServer) RestoreDatabaseBackup(context.Context, *RestoreDatabaseBackupRequest) (*RestoreDatabaseBackupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreDatabaseBackup not implemented")
}
func (UnimplementedDatabaseServiceServer) UpgradeDatabase(context.Context, *UpgradeDatabaseRequest) (*UpgradeDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpgradeDatabase not implemented")
}
func (UnimplementedDatabaseServiceServer) mustEmbedUnimplementedDatabaseServiceServer() {}
func (UnimplementedDatabaseServiceServer) testEmbeddedByValue()                         {}

// UnsafeDatabaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatabaseServiceServer will
// result in compilation errors.
type UnsafeDatabaseServiceServer interface {
	mustEmbedUnimplementedDatabaseServiceServer()
}

func RegisterDatabaseServiceServer(s grpc.ServiceRegistrar, srv DatabaseServiceServer) {
	// If the following call panics, it indicates UnimplementedDatabaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatabaseService_ServiceDesc, srv)
}

func _DatabaseService_CreateDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).CreateDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_CreateDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).CreateDatabase(ctx, req.(*CreateDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_GetDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).GetDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_GetDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).GetDatabase(ctx, req.(*GetDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_ListDatabases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatabasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).ListDatabases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_ListDatabases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).ListDatabases(ctx, req.(*ListDatabasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_DeleteDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).DeleteDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_DeleteDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).DeleteDatabase(ctx, req.(*DeleteDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_SuspendDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).SuspendDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_SuspendDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).SuspendDatabase(ctx, req.(*SuspendDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_ResumeDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).ResumeDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_ResumeDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).ResumeDatabase(ctx, req.(*ResumeDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_RetryDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).RetryDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_RetryDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).RetryDatabase(ctx, req.(*RetryDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_UpdateDatabaseSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDatabaseSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).UpdateDatabaseSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_UpdateDatabaseSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).UpdateDatabaseSettings(ctx, req.(*UpdateDatabaseSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_RotateDatabaseCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateDatabaseCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).RotateDatabaseCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_RotateDatabaseCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).RotateDatabaseCredentials(ctx, req.(*RotateDatabaseCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_RevealDatabaseCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevealDatabaseCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).RevealDatabaseCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_RevealDatabaseCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).RevealDatabaseCredentials(ctx, req.(*RevealDatabaseCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_TriggerDatabaseBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerDatabaseBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).TriggerDatabaseBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_TriggerDatabaseBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).TriggerDatabaseBackup(ctx, req.(*TriggerDatabaseBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_ListDatabaseBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatabaseBackupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).ListDatabaseBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_ListDatabaseBackups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).ListDatabaseBackups(ctx, req.(*ListDatabaseBackupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_RestoreDatabaseBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreDatabaseBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).RestoreDatabaseBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_RestoreDatabaseBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).RestoreDatabaseBackup(ctx, req.(*RestoreDatabaseBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_UpgradeDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).UpgradeDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_UpgradeDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).UpgradeDatabase(ctx, req.(*UpgradeDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DatabaseService_ServiceDesc is the grpc.ServiceDesc for DatabaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatabaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleetly.server.v1.DatabaseService",
	HandlerType: (*DatabaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDatabase",
			Handler:    _DatabaseService_CreateDatabase_Handler,
		},
		{
			MethodName: "GetDatabase",
			Handler:    _DatabaseService_GetDatabase_Handler,
		},
		{
			MethodName: "ListDatabases",
			Handler:    _DatabaseService_ListDatabases_Handler,
		},
		{
			MethodName: "DeleteDatabase",
			Handler:    _DatabaseService_DeleteDatabase_Handler,
		},
		{
			MethodName: "SuspendDatabase",
			Handler:    _DatabaseService_SuspendDatabase_Handler,
		},
		{
			MethodName: "ResumeDatabase",
			Handler:    _DatabaseService_ResumeDatabase_Handler,
		},
		{
			MethodName: "RetryDatabase",
			Handler:    _DatabaseService_RetryDatabase_Handler,
		},
		{
			MethodName: "UpdateDatabaseSettings",
			Handler:    _DatabaseService_UpdateDatabaseSettings_Handler,
		},
		{
			MethodName: "RotateDatabaseCredentials",
			Handler:    _DatabaseService_RotateDatabaseCredentials_Handler,
		},
		{
			MethodName: "RevealDatabaseCredentials",
			Handler:    _DatabaseService_RevealDatabaseCredentials_Handler,
		},
		{
			MethodName: "TriggerDatabaseBackup",
			Handler:    _DatabaseService_TriggerDatabaseBackup_Handler,
		},
		{
			MethodName: "ListDatabaseBackups",
			Handler:    _DatabaseService_ListDatabaseBackups_Handler,
		},
		{
			MethodName: "RestoreDatabaseBackup",
			Handler:    _DatabaseService_RestoreDatabaseBackup_Handler,
		},
		{
			MethodName: "UpgradeDatabase",
			Handler:    _DatabaseService_UpgradeDatabase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fleetly/server/v1/database.proto",
}
