// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: fleetly/server/v1/drift.proto

package serverv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/fleetlyrun/fleetly/genproto/fleetly/annotations/v1"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShowDriftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowDriftRequest) Reset() {
	*x = ShowDriftRequest{}
	mi := &file_fleetly_server_v1_drift_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowDriftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowDriftRequest) ProtoMessage() {}

func (x *ShowDriftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_drift_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowDriftRequest.ProtoReflect.Descriptor instead.
func (*ShowDriftRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_drift_proto_rawDescGZIP(), []int{0}
}

func (x *ShowDriftRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

// FieldDiffView 是单字段差异（值均为投影形态：env 只到键名 + key:hash，
// 值明文与长度都不出投影）。
type FieldDiffView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Expected      string                 `protobuf:"bytes,2,opt,name=expected,proto3" json:"expected,omitempty"`
	Actual        string                 `protobuf:"bytes,3,opt,name=actual,proto3" json:"actual,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldDiffView) Reset() {
	*x = FieldDiffView{}
	mi := &file_fleetly_server_v1_drift_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldDiffView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDiffView) ProtoMessage() {}

func (x *FieldDiffView) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_drift_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDiffView.ProtoReflect.Descriptor instead.
func (*FieldDiffView) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_drift_proto_rawDescGZIP(), []int{1}
}

func (x *FieldDiffView) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FieldDiffView) GetExpected() string {
	if x != nil {
		return x.Expected
	}
	return ""
}

func (x *FieldDiffView) GetActual() string {
	if x != nil {
		return x.Actual
	}
	return ""
}

// ServiceDriftView 是单服务的漂移结果（missing = 期望服务不存在；extra =
// 期望集之外的多余受管服务）。
type ServiceDriftView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Drifted       bool                   `protobuf:"varint,2,opt,name=drifted,proto3" json:"drifted,omitempty"`
	Missing       bool                   `protobuf:"varint,3,opt,name=missing,proto3" json:"missing,omitempty"`
	Extra         bool                   `protobuf:"varint,4,opt,name=extra,proto3" json:"extra,omitempty"`
	Diff          []*FieldDiffView       `protobuf:"bytes,5,rep,name=diff,proto3" json:"diff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDriftView) Reset() {
	*x = ServiceDriftView{}
	mi := &file_fleetly_server_v1_drift_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDriftView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDriftView) ProtoMessage() {}

func (x *ServiceDriftView) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_drift_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDriftView.ProtoReflect.Descriptor instead.
func (*ServiceDriftView) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_drift_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceDriftView) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ServiceDriftView) GetDrifted() bool {
	if x != nil {
		return x.Drifted
	}
	return false
}

func (x *ServiceDriftView) GetMissing() bool {
	if x != nil {
		return x.Missing
	}
	return false
}

func (x *ServiceDriftView) GetExtra() bool {
	if x != nil {
		return x.Extra
	}
	return false
}

func (x *ServiceDriftView) GetDiff() []*FieldDiffView {
	if x != nil {
		return x.Diff
	}
	return nil
}

type ShowDriftResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	App   string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	// 期望态来源部署（空 = 无成功部署记录，无从判定）。
	DesiredDeployment string              `protobuf:"bytes,2,opt,name=desired_deployment,json=desiredDeployment,proto3" json:"desired_deployment,omitempty"`
	Drifted           bool                `protobuf:"varint,3,opt,name=drifted,proto3" json:"drifted,omitempty"`
	Services          []*ServiceDriftView `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ShowDriftResponse) Reset() {
	*x = ShowDriftResponse{}
	mi := &file_fleetly_server_v1_drift_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowDriftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowDriftResponse) ProtoMessage() {}

func (x *ShowDriftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_drift_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowDriftResponse.ProtoReflect.Descriptor instead.
func (*ShowDriftResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_drift_proto_rawDescGZIP(), []int{3}
}

func (x *ShowDriftResponse) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *ShowDriftResponse) GetDesiredDeployment() string {
	if x != nil {
		return x.DesiredDeployment
	}
	return ""
}

func (x *ShowDriftResponse) GetDrifted() bool {
	if x != nil {
		return x.Drifted
	}
	return false
}

func (x *ShowDriftResponse) GetServices() []*ServiceDriftView {
	if x != nil {
		return x.Services
	}
	return nil
}

type ConvergeDriftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvergeDriftRequest) Reset() {
	*x = ConvergeDriftRequest{}
	mi := &file_fleetly_server_v1_drift_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvergeDriftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvergeDriftRequest) ProtoMessage() {}

func (x *ConvergeDriftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_drift_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvergeDriftRequest.ProtoReflect.Descriptor instead.
func (*ConvergeDriftRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_drift_proto_rawDescGZIP(), []int{4}
}

func (x *ConvergeDriftRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

type ConvergeDriftResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	App   string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	// 收敛基准部署（期望态快照来源；收敛入队为准入重放，状态经部署面跟踪）。
	DeploymentId  string `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	DesiredHash   string `protobuf:"bytes,3,opt,name=desired_hash,json=desiredHash,proto3" json:"desired_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvergeDriftResponse) Reset() {
	*x = ConvergeDriftResponse{}
	mi := &file_fleetly_server_v1_drift_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvergeDriftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvergeDriftResponse) ProtoMessage() {}

func (x *ConvergeDriftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_drift_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvergeDriftResponse.ProtoReflect.Descriptor instead.
func (*ConvergeDriftResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_drift_proto_rawDescGZIP(), []int{5}
}

func (x *ConvergeDriftResponse) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *ConvergeDriftResponse) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *ConvergeDriftResponse) GetDesiredHash() string {
	if x != nil {
		return x.DesiredHash
	}
	return ""
}

type SetDriftConvergeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriftConvergeRequest) Reset() {
	*x = SetDriftConvergeRequest{}
	mi := &file_fleetly_server_v1_drift_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriftConvergeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriftConvergeRequest) ProtoMessage() {}

func (x *SetDriftConvergeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_drift_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriftConvergeRequest.ProtoReflect.Descriptor instead.
func (*SetDriftConvergeRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_drift_proto_rawDescGZIP(), []int{6}
}

func (x *SetDriftConvergeRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *SetDriftConvergeRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SetDriftConvergeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriftConvergeResponse) Reset() {
	*x = SetDriftConvergeResponse{}
	mi := &file_fleetly_server_v1_drift_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriftConvergeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriftConvergeResponse) ProtoMessage() {}

func (x *SetDriftConvergeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_drift_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriftConvergeResponse.ProtoReflect.Descriptor instead.
func (*SetDriftConvergeResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_drift_proto_rawDescGZIP(), []int{7}
}

func (x *SetDriftConvergeResponse) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *SetDriftConvergeResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

var File_fleetly_server_v1_drift_proto protoreflect.FileDescriptor

const file_fleetly_server_v1_drift_proto_rawDesc = "" +
	"\n" +
	"\x1dfleetly/server/v1/drift.proto\x12\x11fleetly.server.v1\x1a\x1bbuf/validate/validate.proto\x1a(fleetly/annotations/v1/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"-\n" +
	"\x10ShowDriftRequest\x12\x19\n" +
	"\x03app\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03app\"Y\n" +
	"\rFieldDiffView\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1a\n" +
	"\bexpected\x18\x02 \x01(\tR\bexpected\x12\x16\n" +
	"\x06actual\x18\x03 \x01(\tR\x06actual\"\xac\x01\n" +
	"\x10ServiceDriftView\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x18\n" +
	"\adrifted\x18\x02 \x01(\bR\adrifted\x12\x18\n" +
	"\amissing\x18\x03 \x01(\bR\amissing\x12\x14\n" +
	"\x05extra\x18\x04 \x01(\bR\x05extra\x124\n" +
	"\x04diff\x18\x05 \x03(\v2 .fleetly.server.v1.FieldDiffViewR\x04diff\"\xaf\x01\n" +
	"\x11ShowDriftResponse\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12-\n" +
	"\x12desired_deployment\x18\x02 \x01(\tR\x11desiredDeployment\x12\x18\n" +
	"\adrifted\x18\x03 \x01(\bR\adrifted\x12?\n" +
	"\bservices\x18\x04 \x03(\v2#.fleetly.server.v1.ServiceDriftViewR\bservices\"1\n" +
	"\x14ConvergeDriftRequest\x12\x19\n" +
	"\x03app\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03app\"q\n" +
	"\x15ConvergeDriftResponse\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12#\n" +
	"\rdeployment_id\x18\x02 \x01(\tR\fdeploymentId\x12!\n" +
	"\fdesired_hash\x18\x03 \x01(\tR\vdesiredHash\"N\n" +
	"\x17SetDriftConvergeRequest\x12\x19\n" +
	"\x03app\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03app\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"F\n" +
	"\x18SetDriftConvergeResponse\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled2\xca\x03\n" +
	"\fDriftService\x12|\n" +
	"\tShowDrift\x12#.fleetly.server.v1.ShowDriftRequest\x1a$.fleetly.server.v1.ShowDriftResponse\"$\x82\xb5\x18\x04read\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/apps/{app}/drift\x12\x96\x01\n" +
	"\rConvergeDrift\x12'.fleetly.server.v1.ConvergeDriftRequest\x1a(.fleetly.server.v1.ConvergeDriftResponse\"2\x82\xb5\x18\x06deploy\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/apps/{app}/drift/converge\x12\xa2\x01\n" +
	"\x10SetDriftConverge\x12*.fleetly.server.v1.SetDriftConvergeRequest\x1a+.fleetly.server.v1.SetDriftConvergeResponse\"5\x82\xb5\x18\x06deploy\x82\xd3\xe4\x93\x02%:\x01*\x1a /v1/apps/{app}/drift/convergenceB\x98\x01\x92ARRP\n" +
	"\adefault\x12E\n" +
	"\x1dAn unexpected error response.\x12$\n" +
	"\"\x1a .fleetly.shared.v1.ErrorResponseZAgithub.com/fleetlyrun/fleetly/genproto/fleetly/server/v1;serverv1b\x06proto3"

var (
	file_fleetly_server_v1_drift_proto_rawDescOnce sync.Once
	file_fleetly_server_v1_drift_proto_rawDescData []byte
)

func file_fleetly_server_v1_drift_proto_rawDescGZIP() []byte {
	file_fleetly_server_v1_drift_proto_rawDescOnce.Do(func() {
		file_fleetly_server_v1_drift_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleetly_server_v1_drift_proto_rawDesc), len(file_fleetly_server_v1_drift_proto_rawDesc)))
	})
	return file_fleetly_server_v1_drift_proto_rawDescData
}

var file_fleetly_server_v1_drift_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_fleetly_server_v1_drift_proto_goTypes = []any{
	(*ShowDriftRequest)(nil),         // 0: fleetly.server.v1.ShowDriftRequest
	(*FieldDiffView)(nil),            // 1: fleetly.server.v1.FieldDiffView
	(*ServiceDriftView)(nil),         // 2: fleetly.server.v1.ServiceDriftView
	(*ShowDriftResponse)(nil),        // 3: fleetly.server.v1.ShowDriftResponse
	(*ConvergeDriftRequest)(nil),     // 4: fleetly.server.v1.ConvergeDriftRequest
	(*ConvergeDriftResponse)(nil),    // 5: fleetly.server.v1.ConvergeDriftResponse
	(*SetDriftConvergeRequest)(nil),  // 6: fleetly.server.v1.SetDriftConvergeRequest
	(*SetDriftConvergeResponse)(nil), // 7: fleetly.server.v1.SetDriftConvergeResponse
}
var file_fleetly_server_v1_drift_proto_depIdxs = []int32{
	1, // 0: fleetly.server.v1.ServiceDriftView.diff:type_name -> fleetly.server.v1.FieldDiffView
	2, // 1: fleetly.server.v1.ShowDriftResponse.services:type_name -> fleetly.server.v1.ServiceDriftView
	0, // 2: fleetly.server.v1.DriftService.ShowDrift:input_type -> fleetly.server.v1.ShowDriftRequest
	4, // 3: fleetly.server.v1.DriftService.ConvergeDrift:input_type -> fleetly.server.v1.ConvergeDriftRequest
	6, // 4: fleetly.server.v1.DriftService.SetDriftConverge:input_type -> fleetly.server.v1.SetDriftConvergeRequest
	3, // 5: fleetly.server.v1.DriftService.ShowDrift:output_type -> fleetly.server.v1.ShowDriftResponse
	5, // 6: fleetly.server.v1.DriftService.ConvergeDrift:output_type -> fleetly.server.v1.ConvergeDriftResponse
	7, // 7: fleetly.server.v1.DriftService.SetDriftConverge:output_type -> fleetly.server.v1.SetDriftConvergeResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_fleetly_server_v1_drift_proto_init() }
func file_fleetly_server_v1_drift_proto_init() {
	if File_fleetly_server_v1_drift_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleetly_server_v1_drift_proto_rawDesc), len(file_fleetly_server_v1_drift_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleetly_server_v1_drift_proto_goTypes,
		DependencyIndexes: file_fleetly_server_v1_drift_proto_depIdxs,
		MessageInfos:      file_fleetly_server_v1_drift_proto_msgTypes,
	}.Build()
	File_fleetly_server_v1_drift_proto = out.File
	file_fleetly_server_v1_drift_proto_goTypes = nil
	file_fleetly_server_v1_drift_proto_depIdxs = nil
}
