// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: fleetly/server/v1/events.proto

package serverv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/fleetlyrun/fleetly/genproto/fleetly/annotations/v1"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 游标：返回 seq > since_seq 的事件（升序）；0 = 从保留窗起点。
	SinceSeq      int64 `protobuf:"varint,1,opt,name=since_seq,json=sinceSeq,proto3" json:"since_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEventsRequest) Reset() {
	*x = WatchEventsRequest{}
	mi := &file_fleetly_server_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEventsRequest) ProtoMessage() {}

func (x *WatchEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEventsRequest.ProtoReflect.Descriptor instead.
func (*WatchEventsRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *WatchEventsRequest) GetSinceSeq() int64 {
	if x != nil {
		return x.SinceSeq
	}
	return 0
}

// EventView 是事件行投影（payload 为脱敏 JSON 文本；secret 值禁止进入
// 事件——state-model §2.9，采集端已保证）。
type EventView struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seq   int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	At    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	// 注册表内事件名（deployment.succeeded 等）。
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// 主题（deployment:<id> / app:<name> 等）。
	Subject       string `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Payload       string `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventView) Reset() {
	*x = EventView{}
	mi := &file_fleetly_server_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventView) ProtoMessage() {}

func (x *EventView) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventView.ProtoReflect.Descriptor instead.
func (*EventView) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *EventView) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *EventView) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *EventView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventView) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EventView) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// CursorExpiredView 是游标过期断档帧：seq ≤ (oldest_seq - 1) 的事件已被
// 保留策略清理，消费方应以 oldest_seq 重新拉全量。
type CursorExpiredView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldestSeq     int64                  `protobuf:"varint,1,opt,name=oldest_seq,json=oldestSeq,proto3" json:"oldest_seq,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorExpiredView) Reset() {
	*x = CursorExpiredView{}
	mi := &file_fleetly_server_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorExpiredView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorExpiredView) ProtoMessage() {}

func (x *CursorExpiredView) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorExpiredView.ProtoReflect.Descriptor instead.
func (*CursorExpiredView) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *CursorExpiredView) GetOldestSeq() int64 {
	if x != nil {
		return x.OldestSeq
	}
	return 0
}

func (x *CursorExpiredView) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WatchEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*WatchEventsResponse_Event
	//	*WatchEventsResponse_CursorExpired
	Frame         isWatchEventsResponse_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEventsResponse) Reset() {
	*x = WatchEventsResponse{}
	mi := &file_fleetly_server_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEventsResponse) ProtoMessage() {}

func (x *WatchEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEventsResponse.ProtoReflect.Descriptor instead.
func (*WatchEventsResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *WatchEventsResponse) GetFrame() isWatchEventsResponse_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *WatchEventsResponse) GetEvent() *EventView {
	if x != nil {
		if x, ok := x.Frame.(*WatchEventsResponse_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *WatchEventsResponse) GetCursorExpired() *CursorExpiredView {
	if x != nil {
		if x, ok := x.Frame.(*WatchEventsResponse_CursorExpired); ok {
			return x.CursorExpired
		}
	}
	return nil
}

type isWatchEventsResponse_Frame interface {
	isWatchEventsResponse_Frame()
}

type WatchEventsResponse_Event struct {
	Event *EventView `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type WatchEventsResponse_CursorExpired struct {
	CursorExpired *CursorExpiredView `protobuf:"bytes,2,opt,name=cursor_expired,json=cursorExpired,proto3,oneof"`
}

func (*WatchEventsResponse_Event) isWatchEventsResponse_Frame() {}

func (*WatchEventsResponse_CursorExpired) isWatchEventsResponse_Frame() {}

var File_fleetly_server_v1_events_proto protoreflect.FileDescriptor

const file_fleetly_server_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x1efleetly/server/v1/events.proto\x12\x11fleetly.server.v1\x1a\x1bbuf/validate/validate.proto\x1a(fleetly/annotations/v1/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\":\n" +
	"\x12WatchEventsRequest\x12$\n" +
	"\tsince_seq\x18\x01 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\bsinceSeq\"\x91\x01\n" +
	"\tEventView\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12*\n" +
	"\x02at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayload\"L\n" +
	"\x11CursorExpiredView\x12\x1d\n" +
	"\n" +
	"oldest_seq\x18\x01 \x01(\x03R\toldestSeq\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa3\x01\n" +
	"\x13WatchEventsResponse\x124\n" +
	"\x05event\x18\x01 \x01(\v2\x1c.fleetly.server.v1.EventViewH\x00R\x05event\x12M\n" +
	"\x0ecursor_expired\x18\x02 \x01(\v2$.fleetly.server.v1.CursorExpiredViewH\x00R\rcursorExpiredB\a\n" +
	"\x05frame2\x93\x01\n" +
	"\rEventsService\x12\x81\x01\n" +
	"\vWatchEvents\x12%.fleetly.server.v1.WatchEventsRequest\x1a&.fleetly.server.v1.WatchEventsResponse\"!\x82\xb5\x18\x04read\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/events/stream0\x01B\x98\x01\x92ARRP\n" +
	"\adefault\x12E\n" +
	"\x1dAn unexpected error response.\x12$\n" +
	"\"\x1a .fleetly.shared.v1.ErrorResponseZAgithub.com/fleetlyrun/fleetly/genproto/fleetly/server/v1;serverv1b\x06proto3"

var (
	file_fleetly_server_v1_events_proto_rawDescOnce sync.Once
	file_fleetly_server_v1_events_proto_rawDescData []byte
)

func file_fleetly_server_v1_events_proto_rawDescGZIP() []byte {
	file_fleetly_server_v1_events_proto_rawDescOnce.Do(func() {
		file_fleetly_server_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleetly_server_v1_events_proto_rawDesc), len(file_fleetly_server_v1_events_proto_rawDesc)))
	})
	return file_fleetly_server_v1_events_proto_rawDescData
}

var file_fleetly_server_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_fleetly_server_v1_events_proto_goTypes = []any{
	(*WatchEventsRequest)(nil),    // 0: fleetly.server.v1.WatchEventsRequest
	(*EventView)(nil),             // 1: fleetly.server.v1.EventView
	(*CursorExpiredView)(nil),     // 2: fleetly.server.v1.CursorExpiredView
	(*WatchEventsResponse)(nil),   // 3: fleetly.server.v1.WatchEventsResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_fleetly_server_v1_events_proto_depIdxs = []int32{
	4, // 0: fleetly.server.v1.EventView.at:type_name -> google.protobuf.Timestamp
	1, // 1: fleetly.server.v1.WatchEventsResponse.event:type_name -> fleetly.server.v1.EventView
	2, // 2: fleetly.server.v1.WatchEventsResponse.cursor_expired:type_name -> fleetly.server.v1.CursorExpiredView
	0, // 3: fleetly.server.v1.EventsService.WatchEvents:input_type -> fleetly.server.v1.WatchEventsRequest
	3, // 4: fleetly.server.v1.EventsService.WatchEvents:output_type -> fleetly.server.v1.WatchEventsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_fleetly_server_v1_events_proto_init() }
func file_fleetly_server_v1_events_proto_init() {
	if File_fleetly_server_v1_events_proto != nil {
		return
	}
	file_fleetly_server_v1_events_proto_msgTypes[3].OneofWrappers = []any{
		(*WatchEventsResponse_Event)(nil),
		(*WatchEventsResponse_CursorExpired)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleetly_server_v1_events_proto_rawDesc), len(file_fleetly_server_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleetly_server_v1_events_proto_goTypes,
		DependencyIndexes: file_fleetly_server_v1_events_proto_depIdxs,
		MessageInfos:      file_fleetly_server_v1_events_proto_msgTypes,
	}.Build()
	File_fleetly_server_v1_events_proto = out.File
	file_fleetly_server_v1_events_proto_goTypes = nil
	file_fleetly_server_v1_events_proto_depIdxs = nil
}
