// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: fleetly/server/v1/gitkeys.proto

package serverv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/fleetlyrun/fleetly/genproto/fleetly/annotations/v1"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddGitKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OpenSSH authorized_keys 单行形态（ssh-ed25519/ssh-rsa/ecdsa-sha2-*）。
	PublicKey string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// 人读备注（如 "operator laptop"）。
	Note          string `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGitKeyRequest) Reset() {
	*x = AddGitKeyRequest{}
	mi := &file_fleetly_server_v1_gitkeys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGitKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGitKeyRequest) ProtoMessage() {}

func (x *AddGitKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_gitkeys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGitKeyRequest.ProtoReflect.Descriptor instead.
func (*AddGitKeyRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_gitkeys_proto_rawDescGZIP(), []int{0}
}

func (x *AddGitKeyRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *AddGitKeyRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type AddGitKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// SHA256 指纹（"SHA256:<base64>"，ssh-keygen -lf 同格式）。
	Fingerprint   string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	KeyType       string                 `protobuf:"bytes,3,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	Note          string                 `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGitKeyResponse) Reset() {
	*x = AddGitKeyResponse{}
	mi := &file_fleetly_server_v1_gitkeys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGitKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGitKeyResponse) ProtoMessage() {}

func (x *AddGitKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_gitkeys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGitKeyResponse.ProtoReflect.Descriptor instead.
func (*AddGitKeyResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_gitkeys_proto_rawDescGZIP(), []int{1}
}

func (x *AddGitKeyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddGitKeyResponse) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *AddGitKeyResponse) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *AddGitKeyResponse) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *AddGitKeyResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// GitKeyView 是 git 公钥行的无敏感投影（公钥本体为公开材料可回读；平台
// 从不接触私钥）。
type GitKeyView struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fingerprint string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	KeyType     string                 `protobuf:"bytes,3,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	Note        string                 `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 属主用户（W2 §2.3 用户化注记）：非空 = 登录用户自服务注册的 key；
	// 空 = 存量无主键（迁移口径：只读展示归平台管理员/机具令牌全列）。
	UserId        string `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitKeyView) Reset() {
	*x = GitKeyView{}
	mi := &file_fleetly_server_v1_gitkeys_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitKeyView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitKeyView) ProtoMessage() {}

func (x *GitKeyView) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_gitkeys_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitKeyView.ProtoReflect.Descriptor instead.
func (*GitKeyView) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_gitkeys_proto_rawDescGZIP(), []int{2}
}

func (x *GitKeyView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GitKeyView) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *GitKeyView) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *GitKeyView) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *GitKeyView) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GitKeyView) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListGitKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGitKeysRequest) Reset() {
	*x = ListGitKeysRequest{}
	mi := &file_fleetly_server_v1_gitkeys_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGitKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGitKeysRequest) ProtoMessage() {}

func (x *ListGitKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_gitkeys_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGitKeysRequest.ProtoReflect.Descriptor instead.
func (*ListGitKeysRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_gitkeys_proto_rawDescGZIP(), []int{3}
}

type ListGitKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*GitKeyView          `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGitKeysResponse) Reset() {
	*x = ListGitKeysResponse{}
	mi := &file_fleetly_server_v1_gitkeys_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGitKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGitKeysResponse) ProtoMessage() {}

func (x *ListGitKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_gitkeys_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGitKeysResponse.ProtoReflect.Descriptor instead.
func (*ListGitKeysResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_gitkeys_proto_rawDescGZIP(), []int{4}
}

func (x *ListGitKeysResponse) GetKeys() []*GitKeyView {
	if x != nil {
		return x.Keys
	}
	return nil
}

type RemoveGitKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveGitKeyRequest) Reset() {
	*x = RemoveGitKeyRequest{}
	mi := &file_fleetly_server_v1_gitkeys_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveGitKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGitKeyRequest) ProtoMessage() {}

func (x *RemoveGitKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_gitkeys_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGitKeyRequest.ProtoReflect.Descriptor instead.
func (*RemoveGitKeyRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_gitkeys_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveGitKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveGitKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveGitKeyResponse) Reset() {
	*x = RemoveGitKeyResponse{}
	mi := &file_fleetly_server_v1_gitkeys_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveGitKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGitKeyResponse) ProtoMessage() {}

func (x *RemoveGitKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_gitkeys_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGitKeyResponse.ProtoReflect.Descriptor instead.
func (*RemoveGitKeyResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_gitkeys_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveGitKeyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_fleetly_server_v1_gitkeys_proto protoreflect.FileDescriptor

const file_fleetly_server_v1_gitkeys_proto_rawDesc = "" +
	"\n" +
	"\x1ffleetly/server/v1/gitkeys.proto\x12\x11fleetly.server.v1\x1a\x1bbuf/validate/validate.proto\x1a(fleetly/annotations/v1/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"[\n" +
	"\x10AddGitKeyRequest\x12)\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80@R\tpublicKey\x12\x1c\n" +
	"\x04note\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\xc8\x01R\x04note\"\xaf\x01\n" +
	"\x11AddGitKeyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\x12\x19\n" +
	"\bkey_type\x18\x03 \x01(\tR\akeyType\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc1\x01\n" +
	"\n" +
	"GitKeyView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\x12\x19\n" +
	"\bkey_type\x18\x03 \x01(\tR\akeyType\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\"\x14\n" +
	"\x12ListGitKeysRequest\"H\n" +
	"\x13ListGitKeysResponse\x121\n" +
	"\x04keys\x18\x01 \x03(\v2\x1d.fleetly.server.v1.GitKeyViewR\x04keys\".\n" +
	"\x13RemoveGitKeyRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"&\n" +
	"\x14RemoveGitKeyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x8a\x03\n" +
	"\x0eGitKeysService\x12w\n" +
	"\tAddGitKey\x12#.fleetly.server.v1.AddGitKeyRequest\x1a$.fleetly.server.v1.AddGitKeyResponse\"\x1f\x82\xb5\x18\x04read\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/git/keys\x12z\n" +
	"\vListGitKeys\x12%.fleetly.server.v1.ListGitKeysRequest\x1a&.fleetly.server.v1.ListGitKeysResponse\"\x1c\x82\xb5\x18\x04read\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/git/keys\x12\x82\x01\n" +
	"\fRemoveGitKey\x12&.fleetly.server.v1.RemoveGitKeyRequest\x1a'.fleetly.server.v1.RemoveGitKeyResponse\"!\x82\xb5\x18\x04read\x82\xd3\xe4\x93\x02\x13*\x11/v1/git/keys/{id}B\x98\x01\x92ARRP\n" +
	"\adefault\x12E\n" +
	"\x1dAn unexpected error response.\x12$\n" +
	"\"\x1a .fleetly.shared.v1.ErrorResponseZAgithub.com/fleetlyrun/fleetly/genproto/fleetly/server/v1;serverv1b\x06proto3"

var (
	file_fleetly_server_v1_gitkeys_proto_rawDescOnce sync.Once
	file_fleetly_server_v1_gitkeys_proto_rawDescData []byte
)

func file_fleetly_server_v1_gitkeys_proto_rawDescGZIP() []byte {
	file_fleetly_server_v1_gitkeys_proto_rawDescOnce.Do(func() {
		file_fleetly_server_v1_gitkeys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleetly_server_v1_gitkeys_proto_rawDesc), len(file_fleetly_server_v1_gitkeys_proto_rawDesc)))
	})
	return file_fleetly_server_v1_gitkeys_proto_rawDescData
}

var file_fleetly_server_v1_gitkeys_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_fleetly_server_v1_gitkeys_proto_goTypes = []any{
	(*AddGitKeyRequest)(nil),      // 0: fleetly.server.v1.AddGitKeyRequest
	(*AddGitKeyResponse)(nil),     // 1: fleetly.server.v1.AddGitKeyResponse
	(*GitKeyView)(nil),            // 2: fleetly.server.v1.GitKeyView
	(*ListGitKeysRequest)(nil),    // 3: fleetly.server.v1.ListGitKeysRequest
	(*ListGitKeysResponse)(nil),   // 4: fleetly.server.v1.ListGitKeysResponse
	(*RemoveGitKeyRequest)(nil),   // 5: fleetly.server.v1.RemoveGitKeyRequest
	(*RemoveGitKeyResponse)(nil),  // 6: fleetly.server.v1.RemoveGitKeyResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_fleetly_server_v1_gitkeys_proto_depIdxs = []int32{
	7, // 0: fleetly.server.v1.AddGitKeyResponse.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: fleetly.server.v1.GitKeyView.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: fleetly.server.v1.ListGitKeysResponse.keys:type_name -> fleetly.server.v1.GitKeyView
	0, // 3: fleetly.server.v1.GitKeysService.AddGitKey:input_type -> fleetly.server.v1.AddGitKeyRequest
	3, // 4: fleetly.server.v1.GitKeysService.ListGitKeys:input_type -> fleetly.server.v1.ListGitKeysRequest
	5, // 5: fleetly.server.v1.GitKeysService.RemoveGitKey:input_type -> fleetly.server.v1.RemoveGitKeyRequest
	1, // 6: fleetly.server.v1.GitKeysService.AddGitKey:output_type -> fleetly.server.v1.AddGitKeyResponse
	4, // 7: fleetly.server.v1.GitKeysService.ListGitKeys:output_type -> fleetly.server.v1.ListGitKeysResponse
	6, // 8: fleetly.server.v1.GitKeysService.RemoveGitKey:output_type -> fleetly.server.v1.RemoveGitKeyResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_fleetly_server_v1_gitkeys_proto_init() }
func file_fleetly_server_v1_gitkeys_proto_init() {
	if File_fleetly_server_v1_gitkeys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleetly_server_v1_gitkeys_proto_rawDesc), len(file_fleetly_server_v1_gitkeys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleetly_server_v1_gitkeys_proto_goTypes,
		DependencyIndexes: file_fleetly_server_v1_gitkeys_proto_depIdxs,
		MessageInfos:      file_fleetly_server_v1_gitkeys_proto_msgTypes,
	}.Build()
	File_fleetly_server_v1_gitkeys_proto = out.File
	file_fleetly_server_v1_gitkeys_proto_goTypes = nil
	file_fleetly_server_v1_gitkeys_proto_depIdxs = nil
}
