// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: fleetly/server/v1/metrics.proto

package serverv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetricsService_SearchMetrics_FullMethodName    = "/fleetly.server.v1.MetricsService/SearchMetrics"
	MetricsService_GetMetricsStatus_FullMethodName = "/fleetly.server.v1.MetricsService/GetMetricsStatus"
	MetricsService_SetMetricsMode_FullMethodName   = "/fleetly.server.v1.MetricsService/SetMetricsMode"
)

// MetricsServiceClient is the client API for MetricsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MetricsService 是托管 metrics 三件套的设置/状态/查询面（E6 观测专项设计
// §4，W5-S3；D-W5-2 opt-in——metrics.mode 缺省 unset，零新增常驻）。
//
// 诚实口径（设计 §4.2 原文）：**操作员工具，SearchMetrics 的 PromQL 透传、
// 不做查询沙箱**——query 原样转发给托管 VictoriaMetrics（单机版），平台
// 不声称任何查询隔离；坏表达式由 VM 拒绝并以 InvalidArgument 透传错误
// 原文。mode=unset 查询 → E_METRICS_NOT_ENABLED；VM 不可达 →
// E_METRICS_BACKEND_UNAVAILABLE（不返回空序列冒充有数）。
type MetricsServiceClient interface {
	// SearchMetrics 执行 PromQL 区间查询（read scope）：127.0.0.1:8428
	// /api/v1/query_range 的规范化投影（label 集 + {t,v} 点集）。
	SearchMetrics(ctx context.Context, in *SearchMetricsRequest, opts ...grpc.CallOption) (*SearchMetricsResponse, error)
	// GetMetricsStatus 托管 metrics 栈状态视图（read scope）：模式 / 三件
	// 部署态 / 节点上报比 / retention——「N/M nodes reporting」的诚实口径。
	GetMetricsStatus(ctx context.Context, in *GetMetricsStatusRequest, opts ...grpc.CallOption) (*GetMetricsStatusResponse, error)
	// SetMetricsMode 切换 metrics 模式（unset | on）：保存即生效——后台收敛
	// 部署/移除（数据卷保留），deploy scope（同 SetLogsBackend 分级理由）。
	SetMetricsMode(ctx context.Context, in *SetMetricsModeRequest, opts ...grpc.CallOption) (*SetMetricsModeResponse, error)
}

type metricsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsServiceClient(cc grpc.ClientConnInterface) MetricsServiceClient {
	return &metricsServiceClient{cc}
}

func (c *metricsServiceClient) SearchMetrics(ctx context.Context, in *SearchMetricsRequest, opts ...grpc.CallOption) (*SearchMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchMetricsResponse)
	err := c.cc.Invoke(ctx, MetricsService_SearchMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) GetMetricsStatus(ctx context.Context, in *GetMetricsStatusRequest, opts ...grpc.CallOption) (*GetMetricsStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsStatusResponse)
	err := c.cc.Invoke(ctx, MetricsService_GetMetricsStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) SetMetricsMode(ctx context.Context, in *SetMetricsModeRequest, opts ...grpc.CallOption) (*SetMetricsModeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetMetricsModeResponse)
	err := c.cc.Invoke(ctx, MetricsService_SetMetricsMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsServiceServer is the server API for MetricsService service.
// All implementations must embed UnimplementedMetricsServiceServer
// for forward compatibility.
//
// MetricsService 是托管 metrics 三件套的设置/状态/查询面（E6 观测专项设计
// §4，W5-S3；D-W5-2 opt-in——metrics.mode 缺省 unset，零新增常驻）。
//
// 诚实口径（设计 §4.2 原文）：**操作员工具，SearchMetrics 的 PromQL 透传、
// 不做查询沙箱**——query 原样转发给托管 VictoriaMetrics（单机版），平台
// 不声称任何查询隔离；坏表达式由 VM 拒绝并以 InvalidArgument 透传错误
// 原文。mode=unset 查询 → E_METRICS_NOT_ENABLED；VM 不可达 →
// E_METRICS_BACKEND_UNAVAILABLE（不返回空序列冒充有数）。
type MetricsServiceServer interface {
	// SearchMetrics 执行 PromQL 区间查询（read scope）：127.0.0.1:8428
	// /api/v1/query_range 的规范化投影（label 集 + {t,v} 点集）。
	SearchMetrics(context.Context, *SearchMetricsRequest) (*SearchMetricsResponse, error)
	// GetMetricsStatus 托管 metrics 栈状态视图（read scope）：模式 / 三件
	// 部署态 / 节点上报比 / retention——「N/M nodes reporting」的诚实口径。
	GetMetricsStatus(context.Context, *GetMetricsStatusRequest) (*GetMetricsStatusResponse, error)
	// SetMetricsMode 切换 metrics 模式（unset | on）：保存即生效——后台收敛
	// 部署/移除（数据卷保留），deploy scope（同 SetLogsBackend 分级理由）。
	SetMetricsMode(context.Context, *SetMetricsModeRequest) (*SetMetricsModeResponse, error)
	mustEmbedUnimplementedMetricsServiceServer()
}

// UnimplementedMetricsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricsServiceServer struct{}

func (UnimplementedMetricsServiceServer) SearchMetrics(context.Context, *SearchMetricsRequest) (*SearchMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchMetrics not implemented")
}
func (UnimplementedMetricsServiceServer) GetMetricsStatus(context.Context, *GetMetricsStatusRequest) (*GetMetricsStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetricsStatus not implemented")
}
func (UnimplementedMetricsServiceServer) SetMetricsMode(context.Context, *SetMetricsModeRequest) (*SetMetricsModeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMetricsMode not implemented")
}
func (UnimplementedMetricsServiceServer) mustEmbedUnimplementedMetricsServiceServer() {}
func (UnimplementedMetricsServiceServer) testEmbeddedByValue()                        {}

// UnsafeMetricsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsServiceServer will
// result in compilation errors.
type UnsafeMetricsServiceServer interface {
	mustEmbedUnimplementedMetricsServiceServer()
}

func RegisterMetricsServiceServer(s grpc.ServiceRegistrar, srv MetricsServiceServer) {
	// If the following call panics, it indicates UnimplementedMetricsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricsService_ServiceDesc, srv)
}

func _MetricsService_SearchMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).SearchMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_SearchMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).SearchMetrics(ctx, req.(*SearchMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_GetMetricsStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).GetMetricsStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_GetMetricsStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).GetMetricsStatus(ctx, req.(*GetMetricsStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_SetMetricsMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMetricsModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).SetMetricsMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_SetMetricsMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).SetMetricsMode(ctx, req.(*SetMetricsModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricsService_ServiceDesc is the grpc.ServiceDesc for MetricsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleetly.server.v1.MetricsService",
	HandlerType: (*MetricsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchMetrics",
			Handler:    _MetricsService_SearchMetrics_Handler,
		},
		{
			MethodName: "GetMetricsStatus",
			Handler:    _MetricsService_GetMetricsStatus_Handler,
		},
		{
			MethodName: "SetMetricsMode",
			Handler:    _MetricsService_SetMetricsMode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fleetly/server/v1/metrics.proto",
}
