// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: fleetly/server/v1/metrics.proto

package serverv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/fleetlyrun/fleetly/genproto/fleetly/annotations/v1"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchMetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PromQL 表达式——**透传**（不转义、不校验语法、无沙箱；VM 裁决）。
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// 时间窗下界；缺省 = 现在回望 1 小时。
	TimeStart *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	// 时间窗上界；缺省 = 现在。
	TimeEnd *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time_end,json=timeEnd,proto3" json:"time_end,omitempty"`
	// 步长秒数（缺省 60）。
	StepSeconds int32 `protobuf:"varint,4,opt,name=step_seconds,json=stepSeconds,proto3" json:"step_seconds,omitempty"`
	// 返回序列数上限（缺省 200，天花板 1000——规范化面截断）。
	Limit         int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMetricsRequest) Reset() {
	*x = SearchMetricsRequest{}
	mi := &file_fleetly_server_v1_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMetricsRequest) ProtoMessage() {}

func (x *SearchMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMetricsRequest.ProtoReflect.Descriptor instead.
func (*SearchMetricsRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *SearchMetricsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchMetricsRequest) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

func (x *SearchMetricsRequest) GetTimeEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeEnd
	}
	return nil
}

func (x *SearchMetricsRequest) GetStepSeconds() int32 {
	if x != nil {
		return x.StepSeconds
	}
	return 0
}

func (x *SearchMetricsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// MetricsPoint 是单个采样点（t = unix 秒；v = 采样值）。
type MetricsPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	T             int64                  `protobuf:"varint,1,opt,name=t,proto3" json:"t,omitempty"`
	V             float64                `protobuf:"fixed64,2,opt,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsPoint) Reset() {
	*x = MetricsPoint{}
	mi := &file_fleetly_server_v1_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsPoint) ProtoMessage() {}

func (x *MetricsPoint) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsPoint.ProtoReflect.Descriptor instead.
func (*MetricsPoint) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *MetricsPoint) GetT() int64 {
	if x != nil {
		return x.T
	}
	return 0
}

func (x *MetricsPoint) GetV() float64 {
	if x != nil {
		return x.V
	}
	return 0
}

// MetricsSeries 是一条时序（label 集原样透传——含 __name__ 原始指标名；
// 函数产出的序列无该 label，透传不补造）。
type MetricsSeries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        map[string]string      `protobuf:"bytes,1,rep,name=metric,proto3" json:"metric,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Points        []*MetricsPoint        `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsSeries) Reset() {
	*x = MetricsSeries{}
	mi := &file_fleetly_server_v1_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsSeries) ProtoMessage() {}

func (x *MetricsSeries) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsSeries.ProtoReflect.Descriptor instead.
func (*MetricsSeries) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *MetricsSeries) GetMetric() map[string]string {
	if x != nil {
		return x.Metric
	}
	return nil
}

func (x *MetricsSeries) GetPoints() []*MetricsPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type SearchMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        []*MetricsSeries       `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMetricsResponse) Reset() {
	*x = SearchMetricsResponse{}
	mi := &file_fleetly_server_v1_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMetricsResponse) ProtoMessage() {}

func (x *SearchMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMetricsResponse.ProtoReflect.Descriptor instead.
func (*SearchMetricsResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *SearchMetricsResponse) GetSeries() []*MetricsSeries {
	if x != nil {
		return x.Series
	}
	return nil
}

type GetMetricsStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsStatusRequest) Reset() {
	*x = GetMetricsStatusRequest{}
	mi := &file_fleetly_server_v1_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsStatusRequest) ProtoMessage() {}

func (x *GetMetricsStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsStatusRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsStatusRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_metrics_proto_rawDescGZIP(), []int{4}
}

// MetricsComponentView 是单件托管服务的部署态投影。
type MetricsComponentView struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 服务是否在位（mode=on 且 false = 后台收敛中——过渡态红面）。
	Exists bool `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	// 实况镜像引用（不在位为空）。
	Image         string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsComponentView) Reset() {
	*x = MetricsComponentView{}
	mi := &file_fleetly_server_v1_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsComponentView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsComponentView) ProtoMessage() {}

func (x *MetricsComponentView) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsComponentView.ProtoReflect.Descriptor instead.
func (*MetricsComponentView) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *MetricsComponentView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricsComponentView) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *MetricsComponentView) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

// GetMetricsStatusResponse 是状态视图（设计 §4.1/§4.2 诚实口径）：mode /
// 三件部署态 / 节点上报比（以实际抓到的 cAdvisor 目标数计——跨节点采集
// 依赖 overlay 数据面，worker 节点缺席时不谎报 M/M）/ retention。
type GetMetricsStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 生效模式：unset | on（缺省 unset；未显式设置时 mode 已投影为缺省值，
	// set 标志区分「缺省生效」）。
	Mode string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	// 该键是否被显式保存过（false = 缺省态生效）。
	ModeSet bool `protobuf:"varint,2,opt,name=mode_set,json=modeSet,proto3" json:"mode_set,omitempty"`
	// 三件部署态（cAdvisor / node_exporter / VictoriaMetrics 固定序）。
	Components []*MetricsComponentView `protobuf:"bytes,3,rep,name=components,proto3" json:"components,omitempty"`
	// 正在向 VM 上报的节点数（up{job="fleetly-cadvisor"} 计数；VM 不可达
	// = 0——配合 components 部署态解读，不单独谎报）。
	NodesReporting int32 `protobuf:"varint,4,opt,name=nodes_reporting,json=nodesReporting,proto3" json:"nodes_reporting,omitempty"`
	// 集群节点总数（观测缓存投影）。
	NodesTotal int32 `protobuf:"varint,5,opt,name=nodes_total,json=nodesTotal,proto3" json:"nodes_total,omitempty"`
	// VM -retentionPeriod 对齐天数（config 键 metrics.retention_days）。
	RetentionDays int32 `protobuf:"varint,6,opt,name=retention_days,json=retentionDays,proto3" json:"retention_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsStatusResponse) Reset() {
	*x = GetMetricsStatusResponse{}
	mi := &file_fleetly_server_v1_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsStatusResponse) ProtoMessage() {}

func (x *GetMetricsStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsStatusResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsStatusResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *GetMetricsStatusResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *GetMetricsStatusResponse) GetModeSet() bool {
	if x != nil {
		return x.ModeSet
	}
	return false
}

func (x *GetMetricsStatusResponse) GetComponents() []*MetricsComponentView {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *GetMetricsStatusResponse) GetNodesReporting() int32 {
	if x != nil {
		return x.NodesReporting
	}
	return 0
}

func (x *GetMetricsStatusResponse) GetNodesTotal() int32 {
	if x != nil {
		return x.NodesTotal
	}
	return 0
}

func (x *GetMetricsStatusResponse) GetRetentionDays() int32 {
	if x != nil {
		return x.RetentionDays
	}
	return 0
}

type SetMetricsModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMetricsModeRequest) Reset() {
	*x = SetMetricsModeRequest{}
	mi := &file_fleetly_server_v1_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMetricsModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMetricsModeRequest) ProtoMessage() {}

func (x *SetMetricsModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMetricsModeRequest.ProtoReflect.Descriptor instead.
func (*SetMetricsModeRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_metrics_proto_rawDescGZIP(), []int{7}
}

func (x *SetMetricsModeRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type SetMetricsModeResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        *GetMetricsStatusResponse `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMetricsModeResponse) Reset() {
	*x = SetMetricsModeResponse{}
	mi := &file_fleetly_server_v1_metrics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMetricsModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMetricsModeResponse) ProtoMessage() {}

func (x *SetMetricsModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_metrics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMetricsModeResponse.ProtoReflect.Descriptor instead.
func (*SetMetricsModeResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_metrics_proto_rawDescGZIP(), []int{8}
}

func (x *SetMetricsModeResponse) GetStatus() *GetMetricsStatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_fleetly_server_v1_metrics_proto protoreflect.FileDescriptor

const file_fleetly_server_v1_metrics_proto_rawDesc = "" +
	"\n" +
	"\x1ffleetly/server/v1/metrics.proto\x12\x11fleetly.server.v1\x1a\x1bbuf/validate/validate.proto\x1a(fleetly/annotations/v1/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xfc\x01\n" +
	"\x14SearchMetricsRequest\x12 \n" +
	"\x05query\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80 R\x05query\x129\n" +
	"\n" +
	"time_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStart\x125\n" +
	"\btime_end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\atimeEnd\x12.\n" +
	"\fstep_seconds\x18\x04 \x01(\x05B\v\xbaH\b\x1a\x06\x18\x80\xa3\x05(\x00R\vstepSeconds\x12 \n" +
	"\x05limit\x18\x05 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xe8\a(\x00R\x05limit\"*\n" +
	"\fMetricsPoint\x12\f\n" +
	"\x01t\x18\x01 \x01(\x03R\x01t\x12\f\n" +
	"\x01v\x18\x02 \x01(\x01R\x01v\"\xc9\x01\n" +
	"\rMetricsSeries\x12D\n" +
	"\x06metric\x18\x01 \x03(\v2,.fleetly.server.v1.MetricsSeries.MetricEntryR\x06metric\x127\n" +
	"\x06points\x18\x02 \x03(\v2\x1f.fleetly.server.v1.MetricsPointR\x06points\x1a9\n" +
	"\vMetricEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\x15SearchMetricsResponse\x128\n" +
	"\x06series\x18\x01 \x03(\v2 .fleetly.server.v1.MetricsSeriesR\x06series\"\x19\n" +
	"\x17GetMetricsStatusRequest\"X\n" +
	"\x14MetricsComponentView\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\"\x83\x02\n" +
	"\x18GetMetricsStatusResponse\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x19\n" +
	"\bmode_set\x18\x02 \x01(\bR\amodeSet\x12G\n" +
	"\n" +
	"components\x18\x03 \x03(\v2'.fleetly.server.v1.MetricsComponentViewR\n" +
	"components\x12'\n" +
	"\x0fnodes_reporting\x18\x04 \x01(\x05R\x0enodesReporting\x12\x1f\n" +
	"\vnodes_total\x18\x05 \x01(\x05R\n" +
	"nodesTotal\x12%\n" +
	"\x0eretention_days\x18\x06 \x01(\x05R\rretentionDays\"=\n" +
	"\x15SetMetricsModeRequest\x12$\n" +
	"\x04mode\x18\x01 \x01(\tB\x10\xbaH\rr\vR\x05unsetR\x02onR\x04mode\"]\n" +
	"\x16SetMetricsModeResponse\x12C\n" +
	"\x06status\x18\x01 \x01(\v2+.fleetly.server.v1.GetMetricsStatusResponseR\x06status2\xba\x03\n" +
	"\x0eMetricsService\x12\x86\x01\n" +
	"\rSearchMetrics\x12'.fleetly.server.v1.SearchMetricsRequest\x1a(.fleetly.server.v1.SearchMetricsResponse\"\"\x82\xb5\x18\x04read\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/metrics/search\x12\x8f\x01\n" +
	"\x10GetMetricsStatus\x12*.fleetly.server.v1.GetMetricsStatusRequest\x1a+.fleetly.server.v1.GetMetricsStatusResponse\"\"\x82\xb5\x18\x04read\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/metrics/status\x12\x8c\x01\n" +
	"\x0eSetMetricsMode\x12(.fleetly.server.v1.SetMetricsModeRequest\x1a).fleetly.server.v1.SetMetricsModeResponse\"%\x82\xb5\x18\x06deploy\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/v1/metrics/modeB\x98\x01\x92ARRP\n" +
	"\adefault\x12E\n" +
	"\x1dAn unexpected error response.\x12$\n" +
	"\"\x1a .fleetly.shared.v1.ErrorResponseZAgithub.com/fleetlyrun/fleetly/genproto/fleetly/server/v1;serverv1b\x06proto3"

var (
	file_fleetly_server_v1_metrics_proto_rawDescOnce sync.Once
	file_fleetly_server_v1_metrics_proto_rawDescData []byte
)

func file_fleetly_server_v1_metrics_proto_rawDescGZIP() []byte {
	file_fleetly_server_v1_metrics_proto_rawDescOnce.Do(func() {
		file_fleetly_server_v1_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleetly_server_v1_metrics_proto_rawDesc), len(file_fleetly_server_v1_metrics_proto_rawDesc)))
	})
	return file_fleetly_server_v1_metrics_proto_rawDescData
}

var file_fleetly_server_v1_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_fleetly_server_v1_metrics_proto_goTypes = []any{
	(*SearchMetricsRequest)(nil),     // 0: fleetly.server.v1.SearchMetricsRequest
	(*MetricsPoint)(nil),             // 1: fleetly.server.v1.MetricsPoint
	(*MetricsSeries)(nil),            // 2: fleetly.server.v1.MetricsSeries
	(*SearchMetricsResponse)(nil),    // 3: fleetly.server.v1.SearchMetricsResponse
	(*GetMetricsStatusRequest)(nil),  // 4: fleetly.server.v1.GetMetricsStatusRequest
	(*MetricsComponentView)(nil),     // 5: fleetly.server.v1.MetricsComponentView
	(*GetMetricsStatusResponse)(nil), // 6: fleetly.server.v1.GetMetricsStatusResponse
	(*SetMetricsModeRequest)(nil),    // 7: fleetly.server.v1.SetMetricsModeRequest
	(*SetMetricsModeResponse)(nil),   // 8: fleetly.server.v1.SetMetricsModeResponse
	nil,                              // 9: fleetly.server.v1.MetricsSeries.MetricEntry
	(*timestamppb.Timestamp)(nil),    // 10: google.protobuf.Timestamp
}
var file_fleetly_server_v1_metrics_proto_depIdxs = []int32{
	10, // 0: fleetly.server.v1.SearchMetricsRequest.time_start:type_name -> google.protobuf.Timestamp
	10, // 1: fleetly.server.v1.SearchMetricsRequest.time_end:type_name -> google.protobuf.Timestamp
	9,  // 2: fleetly.server.v1.MetricsSeries.metric:type_name -> fleetly.server.v1.MetricsSeries.MetricEntry
	1,  // 3: fleetly.server.v1.MetricsSeries.points:type_name -> fleetly.server.v1.MetricsPoint
	2,  // 4: fleetly.server.v1.SearchMetricsResponse.series:type_name -> fleetly.server.v1.MetricsSeries
	5,  // 5: fleetly.server.v1.GetMetricsStatusResponse.components:type_name -> fleetly.server.v1.MetricsComponentView
	6,  // 6: fleetly.server.v1.SetMetricsModeResponse.status:type_name -> fleetly.server.v1.GetMetricsStatusResponse
	0,  // 7: fleetly.server.v1.MetricsService.SearchMetrics:input_type -> fleetly.server.v1.SearchMetricsRequest
	4,  // 8: fleetly.server.v1.MetricsService.GetMetricsStatus:input_type -> fleetly.server.v1.GetMetricsStatusRequest
	7,  // 9: fleetly.server.v1.MetricsService.SetMetricsMode:input_type -> fleetly.server.v1.SetMetricsModeRequest
	3,  // 10: fleetly.server.v1.MetricsService.SearchMetrics:output_type -> fleetly.server.v1.SearchMetricsResponse
	6,  // 11: fleetly.server.v1.MetricsService.GetMetricsStatus:output_type -> fleetly.server.v1.GetMetricsStatusResponse
	8,  // 12: fleetly.server.v1.MetricsService.SetMetricsMode:output_type -> fleetly.server.v1.SetMetricsModeResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_fleetly_server_v1_metrics_proto_init() }
func file_fleetly_server_v1_metrics_proto_init() {
	if File_fleetly_server_v1_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleetly_server_v1_metrics_proto_rawDesc), len(file_fleetly_server_v1_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleetly_server_v1_metrics_proto_goTypes,
		DependencyIndexes: file_fleetly_server_v1_metrics_proto_depIdxs,
		MessageInfos:      file_fleetly_server_v1_metrics_proto_msgTypes,
	}.Build()
	File_fleetly_server_v1_metrics_proto = out.File
	file_fleetly_server_v1_metrics_proto_goTypes = nil
	file_fleetly_server_v1_metrics_proto_depIdxs = nil
}
