// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: fleetly/server/v1/runtime.proto

package serverv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuntimeService_ShowAppRuntime_FullMethodName = "/fleetly.server.v1.RuntimeService/ShowAppRuntime"
)

// RuntimeServiceClient is the client API for RuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RuntimeService 是应用运行实况面（2026-09-29 Console IA 重设计，设计
// docs/design/2026-09-29-console-ia-redesign.md §5）：把引擎观测底座已有的
// ServiceList/TaskList（internal/engine/ports.go Substrate 端口）按 app 上抛
// 为只读投影——此前该实况只被引擎观测循环内部消费，Console 无「实际运行的
// 容器」可见面。独立成 service 的理由与 DriftService 同款：运行实况横跨
// deployments 期望快照与 Swarm 实况的对账域，不是部署资源行的 CRUD。
//
// ShowAppRuntime 是即时投影（不写事件不收敛）：服务集 = 期望集（最近
// succeeded 部署快照，声明副本经活覆盖钉入）∪ 实况集（受管长驻服务，
// 一次性 job 豁免）；每服务附全部任务（含历史——swarm task 语义，旧任务
// 下线后仍在列表，desired_state=remove 标注）。env 等敏感值不出投影
// （任务/服务投影只含镜像/状态/时间戳族字段）。
type RuntimeServiceClient interface {
	ShowAppRuntime(ctx context.Context, in *ShowAppRuntimeRequest, opts ...grpc.CallOption) (*ShowAppRuntimeResponse, error)
}

type runtimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeServiceClient(cc grpc.ClientConnInterface) RuntimeServiceClient {
	return &runtimeServiceClient{cc}
}

func (c *runtimeServiceClient) ShowAppRuntime(ctx context.Context, in *ShowAppRuntimeRequest, opts ...grpc.CallOption) (*ShowAppRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowAppRuntimeResponse)
	err := c.cc.Invoke(ctx, RuntimeService_ShowAppRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeServiceServer is the server API for RuntimeService service.
// All implementations must embed UnimplementedRuntimeServiceServer
// for forward compatibility.
//
// RuntimeService 是应用运行实况面（2026-09-29 Console IA 重设计，设计
// docs/design/2026-09-29-console-ia-redesign.md §5）：把引擎观测底座已有的
// ServiceList/TaskList（internal/engine/ports.go Substrate 端口）按 app 上抛
// 为只读投影——此前该实况只被引擎观测循环内部消费，Console 无「实际运行的
// 容器」可见面。独立成 service 的理由与 DriftService 同款：运行实况横跨
// deployments 期望快照与 Swarm 实况的对账域，不是部署资源行的 CRUD。
//
// ShowAppRuntime 是即时投影（不写事件不收敛）：服务集 = 期望集（最近
// succeeded 部署快照，声明副本经活覆盖钉入）∪ 实况集（受管长驻服务，
// 一次性 job 豁免）；每服务附全部任务（含历史——swarm task 语义，旧任务
// 下线后仍在列表，desired_state=remove 标注）。env 等敏感值不出投影
// （任务/服务投影只含镜像/状态/时间戳族字段）。
type RuntimeServiceServer interface {
	ShowAppRuntime(context.Context, *ShowAppRuntimeRequest) (*ShowAppRuntimeResponse, error)
	mustEmbedUnimplementedRuntimeServiceServer()
}

// UnimplementedRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeServiceServer struct{}

func (UnimplementedRuntimeServiceServer) ShowAppRuntime(context.Context, *ShowAppRuntimeRequest) (*ShowAppRuntimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShowAppRuntime not implemented")
}
func (UnimplementedRuntimeServiceServer) mustEmbedUnimplementedRuntimeServiceServer() {}
func (UnimplementedRuntimeServiceServer) testEmbeddedByValue()                        {}

// UnsafeRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeServiceServer will
// result in compilation errors.
type UnsafeRuntimeServiceServer interface {
	mustEmbedUnimplementedRuntimeServiceServer()
}

func RegisterRuntimeServiceServer(s grpc.ServiceRegistrar, srv RuntimeServiceServer) {
	// If the following call panics, it indicates UnimplementedRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuntimeService_ServiceDesc, srv)
}

func _RuntimeService_ShowAppRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowAppRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).ShowAppRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_ShowAppRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).ShowAppRuntime(ctx, req.(*ShowAppRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuntimeService_ServiceDesc is the grpc.ServiceDesc for RuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleetly.server.v1.RuntimeService",
	HandlerType: (*RuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShowAppRuntime",
			Handler:    _RuntimeService_ShowAppRuntime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fleetly/server/v1/runtime.proto",
}
