// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: fleetly/server/v1/secrets.proto

package serverv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/fleetlyrun/fleetly/genproto/fleetly/annotations/v1"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 归属 app 名。
	App string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	// secret 声明名（compose 服务级 secrets 引用的短名；合法 /run/secrets/<name>
	// 文件名字符集 ^[A-Za-z0-9][A-Za-z0-9._-]*$——与 internal/compose 的
	// secret 名校验同规则，注释锚互指）。
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 值（明文；age 加密在服务端。上限 64KiB sanity——Swarm secret 单对象
	// 上界 500KB 的宽松内档；长度进形状层即拒，不落日志）。
	Value         string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSecretRequest) Reset() {
	*x = SetSecretRequest{}
	mi := &file_fleetly_server_v1_secrets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSecretRequest) ProtoMessage() {}

func (x *SetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_secrets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSecretRequest.ProtoReflect.Descriptor instead.
func (*SetSecretRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_secrets_proto_rawDescGZIP(), []int{0}
}

func (x *SetSecretRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *SetSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetSecretRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetSecretResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	App   string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 值指纹（sha256 前 8 hex——「是不是那个值」比对面；值材料零出现）。
	Hash8         string                 `protobuf:"bytes,3,opt,name=hash8,proto3" json:"hash8,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSecretResponse) Reset() {
	*x = SetSecretResponse{}
	mi := &file_fleetly_server_v1_secrets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSecretResponse) ProtoMessage() {}

func (x *SetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_secrets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSecretResponse.ProtoReflect.Descriptor instead.
func (*SetSecretResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_secrets_proto_rawDescGZIP(), []int{1}
}

func (x *SetSecretResponse) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *SetSecretResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetSecretResponse) GetHash8() string {
	if x != nil {
		return x.Hash8
	}
	return ""
}

func (x *SetSecretResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SetSecretResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_fleetly_server_v1_secrets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_secrets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_secrets_proto_rawDescGZIP(), []int{2}
}

func (x *ListSecretsRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

type ListSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*SecretView          `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_fleetly_server_v1_secrets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_secrets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_secrets_proto_rawDescGZIP(), []int{3}
}

func (x *ListSecretsResponse) GetSecrets() []*SecretView {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type RemoveSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSecretRequest) Reset() {
	*x = RemoveSecretRequest{}
	mi := &file_fleetly_server_v1_secrets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSecretRequest) ProtoMessage() {}

func (x *RemoveSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_secrets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSecretRequest.ProtoReflect.Descriptor instead.
func (*RemoveSecretRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_secrets_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveSecretRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *RemoveSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RemoveSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSecretResponse) Reset() {
	*x = RemoveSecretResponse{}
	mi := &file_fleetly_server_v1_secrets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSecretResponse) ProtoMessage() {}

func (x *RemoveSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_secrets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSecretResponse.ProtoReflect.Descriptor instead.
func (*RemoveSecretResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_secrets_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveSecretResponse) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *RemoveSecretResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// SecretView 是平台密钥库条目的只读投影（值/密文/明文零出现——D-DB-7
// 无值读回；hash8 是唯一的值比对面）。
type SecretView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Hash8         string                 `protobuf:"bytes,2,opt,name=hash8,proto3" json:"hash8,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretView) Reset() {
	*x = SecretView{}
	mi := &file_fleetly_server_v1_secrets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretView) ProtoMessage() {}

func (x *SecretView) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_secrets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretView.ProtoReflect.Descriptor instead.
func (*SecretView) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_secrets_proto_rawDescGZIP(), []int{6}
}

func (x *SecretView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretView) GetHash8() string {
	if x != nil {
		return x.Hash8
	}
	return ""
}

func (x *SecretView) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SecretView) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_fleetly_server_v1_secrets_proto protoreflect.FileDescriptor

const file_fleetly_server_v1_secrets_proto_rawDesc = "" +
	"\n" +
	"\x1ffleetly/server/v1/secrets.proto\x12\x11fleetly.server.v1\x1a\x1bbuf/validate/validate.proto\x1a(fleetly/annotations/v1/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x89\x01\n" +
	"\x10SetSecretRequest\x12\x19\n" +
	"\x03app\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03app\x127\n" +
	"\x04name\x18\x02 \x01(\tB#\xbaH r\x1e2\x1c^[A-Za-z0-9][A-Za-z0-9._-]*$R\x04name\x12!\n" +
	"\x05value\x18\x03 \x01(\tB\v\xbaH\br\x06\x10\x01\x18\x80\x80\x04R\x05value\"\xc5\x01\n" +
	"\x11SetSecretResponse\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05hash8\x18\x03 \x01(\tR\x05hash8\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"/\n" +
	"\x12ListSecretsRequest\x12\x19\n" +
	"\x03app\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03app\"N\n" +
	"\x13ListSecretsResponse\x127\n" +
	"\asecrets\x18\x01 \x03(\v2\x1d.fleetly.server.v1.SecretViewR\asecrets\"M\n" +
	"\x13RemoveSecretRequest\x12\x19\n" +
	"\x03app\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03app\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\"<\n" +
	"\x14RemoveSecretResponse\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xac\x01\n" +
	"\n" +
	"SecretView\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05hash8\x18\x02 \x01(\tR\x05hash8\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xae\x03\n" +
	"\x0eSecretsService\x12\x82\x01\n" +
	"\tSetSecret\x12#.fleetly.server.v1.SetSecretRequest\x1a$.fleetly.server.v1.SetSecretResponse\"*\x82\xb5\x18\x05admin\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/apps/{app}/secrets\x12\x84\x01\n" +
	"\vListSecrets\x12%.fleetly.server.v1.ListSecretsRequest\x1a&.fleetly.server.v1.ListSecretsResponse\"&\x82\xb5\x18\x04read\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/apps/{app}/secrets\x12\x8f\x01\n" +
	"\fRemoveSecret\x12&.fleetly.server.v1.RemoveSecretRequest\x1a'.fleetly.server.v1.RemoveSecretResponse\".\x82\xb5\x18\x05admin\x82\xd3\xe4\x93\x02\x1f*\x1d/v1/apps/{app}/secrets/{name}B\x98\x01\x92ARRP\n" +
	"\adefault\x12E\n" +
	"\x1dAn unexpected error response.\x12$\n" +
	"\"\x1a .fleetly.shared.v1.ErrorResponseZAgithub.com/fleetlyrun/fleetly/genproto/fleetly/server/v1;serverv1b\x06proto3"

var (
	file_fleetly_server_v1_secrets_proto_rawDescOnce sync.Once
	file_fleetly_server_v1_secrets_proto_rawDescData []byte
)

func file_fleetly_server_v1_secrets_proto_rawDescGZIP() []byte {
	file_fleetly_server_v1_secrets_proto_rawDescOnce.Do(func() {
		file_fleetly_server_v1_secrets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleetly_server_v1_secrets_proto_rawDesc), len(file_fleetly_server_v1_secrets_proto_rawDesc)))
	})
	return file_fleetly_server_v1_secrets_proto_rawDescData
}

var file_fleetly_server_v1_secrets_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_fleetly_server_v1_secrets_proto_goTypes = []any{
	(*SetSecretRequest)(nil),      // 0: fleetly.server.v1.SetSecretRequest
	(*SetSecretResponse)(nil),     // 1: fleetly.server.v1.SetSecretResponse
	(*ListSecretsRequest)(nil),    // 2: fleetly.server.v1.ListSecretsRequest
	(*ListSecretsResponse)(nil),   // 3: fleetly.server.v1.ListSecretsResponse
	(*RemoveSecretRequest)(nil),   // 4: fleetly.server.v1.RemoveSecretRequest
	(*RemoveSecretResponse)(nil),  // 5: fleetly.server.v1.RemoveSecretResponse
	(*SecretView)(nil),            // 6: fleetly.server.v1.SecretView
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_fleetly_server_v1_secrets_proto_depIdxs = []int32{
	7, // 0: fleetly.server.v1.SetSecretResponse.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: fleetly.server.v1.SetSecretResponse.updated_at:type_name -> google.protobuf.Timestamp
	6, // 2: fleetly.server.v1.ListSecretsResponse.secrets:type_name -> fleetly.server.v1.SecretView
	7, // 3: fleetly.server.v1.SecretView.created_at:type_name -> google.protobuf.Timestamp
	7, // 4: fleetly.server.v1.SecretView.updated_at:type_name -> google.protobuf.Timestamp
	0, // 5: fleetly.server.v1.SecretsService.SetSecret:input_type -> fleetly.server.v1.SetSecretRequest
	2, // 6: fleetly.server.v1.SecretsService.ListSecrets:input_type -> fleetly.server.v1.ListSecretsRequest
	4, // 7: fleetly.server.v1.SecretsService.RemoveSecret:input_type -> fleetly.server.v1.RemoveSecretRequest
	1, // 8: fleetly.server.v1.SecretsService.SetSecret:output_type -> fleetly.server.v1.SetSecretResponse
	3, // 9: fleetly.server.v1.SecretsService.ListSecrets:output_type -> fleetly.server.v1.ListSecretsResponse
	5, // 10: fleetly.server.v1.SecretsService.RemoveSecret:output_type -> fleetly.server.v1.RemoveSecretResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_fleetly_server_v1_secrets_proto_init() }
func file_fleetly_server_v1_secrets_proto_init() {
	if File_fleetly_server_v1_secrets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleetly_server_v1_secrets_proto_rawDesc), len(file_fleetly_server_v1_secrets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleetly_server_v1_secrets_proto_goTypes,
		DependencyIndexes: file_fleetly_server_v1_secrets_proto_depIdxs,
		MessageInfos:      file_fleetly_server_v1_secrets_proto_msgTypes,
	}.Build()
	File_fleetly_server_v1_secrets_proto = out.File
	file_fleetly_server_v1_secrets_proto_goTypes = nil
	file_fleetly_server_v1_secrets_proto_depIdxs = nil
}
