// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: fleetly/server/v1/teams.proto

package serverv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/fleetlyrun/fleetly/genproto/fleetly/annotations/v1"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TeamView 是团队行的无敏感投影。
type TeamView struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 单词制标识（[a-z0-9]{2,32}、全局唯一、不可变；底座命名公式段）。
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	// 人读显示名。
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamView) Reset() {
	*x = TeamView{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamView) ProtoMessage() {}

func (x *TeamView) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamView.ProtoReflect.Descriptor instead.
func (*TeamView) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{0}
}

func (x *TeamView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TeamView) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *TeamView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TeamView) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *TeamView) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamRequest) Reset() {
	*x = CreateTeamRequest{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamRequest) ProtoMessage() {}

func (x *CreateTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTeamRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateTeamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          *TeamView              `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamResponse) Reset() {
	*x = CreateTeamResponse{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamResponse) ProtoMessage() {}

func (x *CreateTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamResponse.ProtoReflect.Descriptor instead.
func (*CreateTeamResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTeamResponse) GetTeam() *TeamView {
	if x != nil {
		return x.Team
	}
	return nil
}

type ListTeamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamsRequest) Reset() {
	*x = ListTeamsRequest{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamsRequest) ProtoMessage() {}

func (x *ListTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamsRequest.ProtoReflect.Descriptor instead.
func (*ListTeamsRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{3}
}

type ListTeamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teams         []*TeamView            `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamsResponse) Reset() {
	*x = ListTeamsResponse{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamsResponse) ProtoMessage() {}

func (x *ListTeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamsResponse.ProtoReflect.Descriptor instead.
func (*ListTeamsResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{4}
}

func (x *ListTeamsResponse) GetTeams() []*TeamView {
	if x != nil {
		return x.Teams
	}
	return nil
}

type GetTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamRequest) Reset() {
	*x = GetTeamRequest{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamRequest) ProtoMessage() {}

func (x *GetTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamRequest.ProtoReflect.Descriptor instead.
func (*GetTeamRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{5}
}

func (x *GetTeamRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          *TeamView              `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamResponse) Reset() {
	*x = GetTeamResponse{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamResponse) ProtoMessage() {}

func (x *GetTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamResponse.ProtoReflect.Descriptor instead.
func (*GetTeamResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{6}
}

func (x *GetTeamResponse) GetTeam() *TeamView {
	if x != nil {
		return x.Team
	}
	return nil
}

type UpdateTeamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 新显示名（slug 不可变——请求无 slug 字段，改 slug 只能重建团队）。
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeamRequest) Reset() {
	*x = UpdateTeamRequest{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamRequest) ProtoMessage() {}

func (x *UpdateTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamRequest.ProtoReflect.Descriptor instead.
func (*UpdateTeamRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTeamRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTeamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          *TeamView              `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeamResponse) Reset() {
	*x = UpdateTeamResponse{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamResponse) ProtoMessage() {}

func (x *UpdateTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamResponse.ProtoReflect.Descriptor instead.
func (*UpdateTeamResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTeamResponse) GetTeam() *TeamView {
	if x != nil {
		return x.Team
	}
	return nil
}

type DeleteTeamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 两段式确认：confirm 必须等于团队 slug（数据/归属安全同 DeleteDatabase
	// 口径）。
	Confirm       string `protobuf:"bytes,2,opt,name=confirm,proto3" json:"confirm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamRequest) Reset() {
	*x = DeleteTeamRequest{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamRequest) ProtoMessage() {}

func (x *DeleteTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeamRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTeamRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteTeamRequest) GetConfirm() string {
	if x != nil {
		return x.Confirm
	}
	return ""
}

type DeleteTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamResponse) Reset() {
	*x = DeleteTeamResponse{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamResponse) ProtoMessage() {}

func (x *DeleteTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamResponse.ProtoReflect.Descriptor instead.
func (*DeleteTeamResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{10}
}

type ListTeamMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamMembersRequest) Reset() {
	*x = ListTeamMembersRequest{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamMembersRequest) ProtoMessage() {}

func (x *ListTeamMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamMembersRequest.ProtoReflect.Descriptor instead.
func (*ListTeamMembersRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{11}
}

func (x *ListTeamMembersRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type TeamMemberView struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TeamId string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 团队角色（owner/admin/developer/viewer 四档，设计 §3.2）。
	Role      string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 属主投影（成员列表的可用性面——email 与显示名；无敏感材料）。
	Email         string `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName   string `protobuf:"bytes,6,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamMemberView) Reset() {
	*x = TeamMemberView{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamMemberView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamMemberView) ProtoMessage() {}

func (x *TeamMemberView) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamMemberView.ProtoReflect.Descriptor instead.
func (*TeamMemberView) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{12}
}

func (x *TeamMemberView) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TeamMemberView) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TeamMemberView) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *TeamMemberView) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TeamMemberView) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TeamMemberView) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type ListTeamMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*TeamMemberView      `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamMembersResponse) Reset() {
	*x = ListTeamMembersResponse{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamMembersResponse) ProtoMessage() {}

func (x *ListTeamMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamMembersResponse.ProtoReflect.Descriptor instead.
func (*ListTeamMembersResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{13}
}

func (x *ListTeamMembersResponse) GetMembers() []*TeamMemberView {
	if x != nil {
		return x.Members
	}
	return nil
}

type SetTeamMemberRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTeamMemberRoleRequest) Reset() {
	*x = SetTeamMemberRoleRequest{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTeamMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTeamMemberRoleRequest) ProtoMessage() {}

func (x *SetTeamMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTeamMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*SetTeamMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{14}
}

func (x *SetTeamMemberRoleRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *SetTeamMemberRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetTeamMemberRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type SetTeamMemberRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *TeamMemberView        `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTeamMemberRoleResponse) Reset() {
	*x = SetTeamMemberRoleResponse{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTeamMemberRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTeamMemberRoleResponse) ProtoMessage() {}

func (x *SetTeamMemberRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTeamMemberRoleResponse.ProtoReflect.Descriptor instead.
func (*SetTeamMemberRoleResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{15}
}

func (x *SetTeamMemberRoleResponse) GetMember() *TeamMemberView {
	if x != nil {
		return x.Member
	}
	return nil
}

type RemoveTeamMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTeamMemberRequest) Reset() {
	*x = RemoveTeamMemberRequest{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTeamMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTeamMemberRequest) ProtoMessage() {}

func (x *RemoveTeamMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTeamMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveTeamMemberRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveTeamMemberRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *RemoveTeamMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveTeamMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTeamMemberResponse) Reset() {
	*x = RemoveTeamMemberResponse{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTeamMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTeamMemberResponse) ProtoMessage() {}

func (x *RemoveTeamMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTeamMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveTeamMemberResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{17}
}

type CreateInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInviteRequest) Reset() {
	*x = CreateInviteRequest{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteRequest) ProtoMessage() {}

func (x *CreateInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteRequest.ProtoReflect.Descriptor instead.
func (*CreateInviteRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{18}
}

func (x *CreateInviteRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *CreateInviteRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateInviteRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type InviteView struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TeamId string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// 被邀邮箱（小写归一）。
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role  string `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	// 过期时刻（创建 + 7 天；一次性窗口）。
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 已接受/已吊销时输出对应时刻；未消费时不输出。
	AcceptedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=accepted_at,json=acceptedAt,proto3" json:"accepted_at,omitempty"`
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteView) Reset() {
	*x = InviteView{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteView) ProtoMessage() {}

func (x *InviteView) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteView.ProtoReflect.Descriptor instead.
func (*InviteView) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{19}
}

func (x *InviteView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InviteView) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *InviteView) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InviteView) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *InviteView) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *InviteView) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *InviteView) GetAcceptedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AcceptedAt
	}
	return nil
}

func (x *InviteView) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

type CreateInviteResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Invite *InviteView            `protobuf:"bytes,1,opt,name=invite,proto3" json:"invite,omitempty"`
	// 明文一次性 token（sha256 入库）：仅本次响应可见，用于拼邀请链接
	// console/auth/invite?token=…（无 SMTP 直出供复制，设计 §3.1）。
	Token         string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInviteResponse) Reset() {
	*x = CreateInviteResponse{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteResponse) ProtoMessage() {}

func (x *CreateInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteResponse.ProtoReflect.Descriptor instead.
func (*CreateInviteResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{20}
}

func (x *CreateInviteResponse) GetInvite() *InviteView {
	if x != nil {
		return x.Invite
	}
	return nil
}

func (x *CreateInviteResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ListTeamInvitesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamInvitesRequest) Reset() {
	*x = ListTeamInvitesRequest{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamInvitesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamInvitesRequest) ProtoMessage() {}

func (x *ListTeamInvitesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamInvitesRequest.ProtoReflect.Descriptor instead.
func (*ListTeamInvitesRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{21}
}

func (x *ListTeamInvitesRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type ListTeamInvitesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invites       []*InviteView          `protobuf:"bytes,1,rep,name=invites,proto3" json:"invites,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamInvitesResponse) Reset() {
	*x = ListTeamInvitesResponse{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamInvitesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamInvitesResponse) ProtoMessage() {}

func (x *ListTeamInvitesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamInvitesResponse.ProtoReflect.Descriptor instead.
func (*ListTeamInvitesResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{22}
}

func (x *ListTeamInvitesResponse) GetInvites() []*InviteView {
	if x != nil {
		return x.Invites
	}
	return nil
}

type RevokeInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	InviteId      string                 `protobuf:"bytes,2,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeInviteRequest) Reset() {
	*x = RevokeInviteRequest{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeInviteRequest) ProtoMessage() {}

func (x *RevokeInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeInviteRequest.ProtoReflect.Descriptor instead.
func (*RevokeInviteRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{23}
}

func (x *RevokeInviteRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *RevokeInviteRequest) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

type RevokeInviteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeInviteResponse) Reset() {
	*x = RevokeInviteResponse{}
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeInviteResponse) ProtoMessage() {}

func (x *RevokeInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_teams_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeInviteResponse.ProtoReflect.Descriptor instead.
func (*RevokeInviteResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_teams_proto_rawDescGZIP(), []int{24}
}

var File_fleetly_server_v1_teams_proto protoreflect.FileDescriptor

const file_fleetly_server_v1_teams_proto_rawDesc = "" +
	"\n" +
	"\x1dfleetly/server/v1/teams.proto\x12\x11fleetly.server.v1\x1a\x1bbuf/validate/validate.proto\x1a(fleetly/annotations/v1/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x9c\x01\n" +
	"\bTeamView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"c\n" +
	"\x11CreateTeamRequest\x12/\n" +
	"\x04slug\x18\x01 \x01(\tB\x1b\xbaH\x18r\x16\x10\x02\x18 2\x10^[a-z0-9]{2,32}$R\x04slug\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\x04name\"E\n" +
	"\x12CreateTeamResponse\x12/\n" +
	"\x04team\x18\x01 \x01(\v2\x1b.fleetly.server.v1.TeamViewR\x04team\"\x12\n" +
	"\x10ListTeamsRequest\"F\n" +
	"\x11ListTeamsResponse\x121\n" +
	"\x05teams\x18\x01 \x03(\v2\x1b.fleetly.server.v1.TeamViewR\x05teams\")\n" +
	"\x0eGetTeamRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"B\n" +
	"\x0fGetTeamResponse\x12/\n" +
	"\x04team\x18\x01 \x01(\v2\x1b.fleetly.server.v1.TeamViewR\x04team\"K\n" +
	"\x11UpdateTeamRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\x04name\"E\n" +
	"\x12UpdateTeamResponse\x12/\n" +
	"\x04team\x18\x01 \x01(\v2\x1b.fleetly.server.v1.TeamViewR\x04team\"O\n" +
	"\x11DeleteTeamRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x12!\n" +
	"\aconfirm\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\aconfirm\"\x14\n" +
	"\x12DeleteTeamResponse\":\n" +
	"\x16ListTeamMembersRequest\x12 \n" +
	"\ateam_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06teamId\"\xca\x01\n" +
	"\x0eTeamMemberView\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x06 \x01(\tR\vdisplayName\"V\n" +
	"\x17ListTeamMembersResponse\x12;\n" +
	"\amembers\x18\x01 \x03(\v2!.fleetly.server.v1.TeamMemberViewR\amembers\"\x9a\x01\n" +
	"\x18SetTeamMemberRoleRequest\x12 \n" +
	"\ateam_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06teamId\x12 \n" +
	"\auser_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\x12:\n" +
	"\x04role\x18\x03 \x01(\tB&\xbaH#r!R\x05ownerR\x05adminR\tdeveloperR\x06viewerR\x04role\"V\n" +
	"\x19SetTeamMemberRoleResponse\x129\n" +
	"\x06member\x18\x01 \x01(\v2!.fleetly.server.v1.TeamMemberViewR\x06member\"]\n" +
	"\x17RemoveTeamMemberRequest\x12 \n" +
	"\ateam_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06teamId\x12 \n" +
	"\auser_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\"\x1a\n" +
	"\x18RemoveTeamMemberResponse\"\x97\x01\n" +
	"\x13CreateInviteRequest\x12 \n" +
	"\ateam_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06teamId\x12\"\n" +
	"\x05email\x18\x02 \x01(\tB\f\xbaH\tr\a\x10\x03\x18\xfe\x01`\x01R\x05email\x12:\n" +
	"\x04role\x18\x03 \x01(\tB&\xbaH#r!R\x05ownerR\x05adminR\tdeveloperR\x06viewerR\x04role\"\xcd\x02\n" +
	"\n" +
	"InviteView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vaccepted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"acceptedAt\x129\n" +
	"\n" +
	"revoked_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\"c\n" +
	"\x14CreateInviteResponse\x125\n" +
	"\x06invite\x18\x01 \x01(\v2\x1d.fleetly.server.v1.InviteViewR\x06invite\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\":\n" +
	"\x16ListTeamInvitesRequest\x12 \n" +
	"\ateam_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06teamId\"R\n" +
	"\x17ListTeamInvitesResponse\x127\n" +
	"\ainvites\x18\x01 \x03(\v2\x1d.fleetly.server.v1.InviteViewR\ainvites\"]\n" +
	"\x13RevokeInviteRequest\x12 \n" +
	"\ateam_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06teamId\x12$\n" +
	"\tinvite_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\binviteId\"\x16\n" +
	"\x14RevokeInviteResponse2\x9b\f\n" +
	"\fTeamsService\x12w\n" +
	"\n" +
	"CreateTeam\x12$.fleetly.server.v1.CreateTeamRequest\x1a%.fleetly.server.v1.CreateTeamResponse\"\x1c\x82\xb5\x18\x04read\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/teams\x12q\n" +
	"\tListTeams\x12#.fleetly.server.v1.ListTeamsRequest\x1a$.fleetly.server.v1.ListTeamsResponse\"\x19\x82\xb5\x18\x04read\x82\xd3\xe4\x93\x02\v\x12\t/v1/teams\x12p\n" +
	"\aGetTeam\x12!.fleetly.server.v1.GetTeamRequest\x1a\".fleetly.server.v1.GetTeamResponse\"\x1e\x82\xb5\x18\x04read\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/teams/{id}\x12|\n" +
	"\n" +
	"UpdateTeam\x12$.fleetly.server.v1.UpdateTeamRequest\x1a%.fleetly.server.v1.UpdateTeamResponse\"!\x82\xb5\x18\x04read\x82\xd3\xe4\x93\x02\x13:\x01*2\x0e/v1/teams/{id}\x12y\n" +
	"\n" +
	"DeleteTeam\x12$.fleetly.server.v1.DeleteTeamRequest\x1a%.fleetly.server.v1.DeleteTeamResponse\"\x1e\x82\xb5\x18\x04read\x82\xd3\xe4\x93\x02\x10*\x0e/v1/teams/{id}\x12\x95\x01\n" +
	"\x0fListTeamMembers\x12).fleetly.server.v1.ListTeamMembersRequest\x1a*.fleetly.server.v1.ListTeamMembersResponse\"+\x82\xb5\x18\x04read\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/teams/{team_id}/members\x12\xa7\x01\n" +
	"\x11SetTeamMemberRole\x12+.fleetly.server.v1.SetTeamMemberRoleRequest\x1a,.fleetly.server.v1.SetTeamMemberRoleResponse\"7\x82\xb5\x18\x04read\x82\xd3\xe4\x93\x02):\x01*\"$/v1/teams/{team_id}/members:set-role\x12\xa2\x01\n" +
	"\x10RemoveTeamMember\x12*.fleetly.server.v1.RemoveTeamMemberRequest\x1a+.fleetly.server.v1.RemoveTeamMemberResponse\"5\x82\xb5\x18\x04read\x82\xd3\xe4\x93\x02'*%/v1/teams/{team_id}/members/{user_id}\x12\x8f\x01\n" +
	"\fCreateInvite\x12&.fleetly.server.v1.CreateInviteRequest\x1a'.fleetly.server.v1.CreateInviteResponse\".\x82\xb5\x18\x04read\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/teams/{team_id}/invites\x12\x95\x01\n" +
	"\x0fListTeamInvites\x12).fleetly.server.v1.ListTeamInvitesRequest\x1a*.fleetly.server.v1.ListTeamInvitesResponse\"+\x82\xb5\x18\x04read\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/teams/{team_id}/invites\x12\xa2\x01\n" +
	"\fRevokeInvite\x12&.fleetly.server.v1.RevokeInviteRequest\x1a'.fleetly.server.v1.RevokeInviteResponse\"A\x82\xb5\x18\x04read\x82\xd3\xe4\x93\x023:\x01*\"./v1/teams/{team_id}/invites/{invite_id}:revokeB\x98\x01\x92ARRP\n" +
	"\adefault\x12E\n" +
	"\x1dAn unexpected error response.\x12$\n" +
	"\"\x1a .fleetly.shared.v1.ErrorResponseZAgithub.com/fleetlyrun/fleetly/genproto/fleetly/server/v1;serverv1b\x06proto3"

var (
	file_fleetly_server_v1_teams_proto_rawDescOnce sync.Once
	file_fleetly_server_v1_teams_proto_rawDescData []byte
)

func file_fleetly_server_v1_teams_proto_rawDescGZIP() []byte {
	file_fleetly_server_v1_teams_proto_rawDescOnce.Do(func() {
		file_fleetly_server_v1_teams_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleetly_server_v1_teams_proto_rawDesc), len(file_fleetly_server_v1_teams_proto_rawDesc)))
	})
	return file_fleetly_server_v1_teams_proto_rawDescData
}

var file_fleetly_server_v1_teams_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_fleetly_server_v1_teams_proto_goTypes = []any{
	(*TeamView)(nil),                  // 0: fleetly.server.v1.TeamView
	(*CreateTeamRequest)(nil),         // 1: fleetly.server.v1.CreateTeamRequest
	(*CreateTeamResponse)(nil),        // 2: fleetly.server.v1.CreateTeamResponse
	(*ListTeamsRequest)(nil),          // 3: fleetly.server.v1.ListTeamsRequest
	(*ListTeamsResponse)(nil),         // 4: fleetly.server.v1.ListTeamsResponse
	(*GetTeamRequest)(nil),            // 5: fleetly.server.v1.GetTeamRequest
	(*GetTeamResponse)(nil),           // 6: fleetly.server.v1.GetTeamResponse
	(*UpdateTeamRequest)(nil),         // 7: fleetly.server.v1.UpdateTeamRequest
	(*UpdateTeamResponse)(nil),        // 8: fleetly.server.v1.UpdateTeamResponse
	(*DeleteTeamRequest)(nil),         // 9: fleetly.server.v1.DeleteTeamRequest
	(*DeleteTeamResponse)(nil),        // 10: fleetly.server.v1.DeleteTeamResponse
	(*ListTeamMembersRequest)(nil),    // 11: fleetly.server.v1.ListTeamMembersRequest
	(*TeamMemberView)(nil),            // 12: fleetly.server.v1.TeamMemberView
	(*ListTeamMembersResponse)(nil),   // 13: fleetly.server.v1.ListTeamMembersResponse
	(*SetTeamMemberRoleRequest)(nil),  // 14: fleetly.server.v1.SetTeamMemberRoleRequest
	(*SetTeamMemberRoleResponse)(nil), // 15: fleetly.server.v1.SetTeamMemberRoleResponse
	(*RemoveTeamMemberRequest)(nil),   // 16: fleetly.server.v1.RemoveTeamMemberRequest
	(*RemoveTeamMemberResponse)(nil),  // 17: fleetly.server.v1.RemoveTeamMemberResponse
	(*CreateInviteRequest)(nil),       // 18: fleetly.server.v1.CreateInviteRequest
	(*InviteView)(nil),                // 19: fleetly.server.v1.InviteView
	(*CreateInviteResponse)(nil),      // 20: fleetly.server.v1.CreateInviteResponse
	(*ListTeamInvitesRequest)(nil),    // 21: fleetly.server.v1.ListTeamInvitesRequest
	(*ListTeamInvitesResponse)(nil),   // 22: fleetly.server.v1.ListTeamInvitesResponse
	(*RevokeInviteRequest)(nil),       // 23: fleetly.server.v1.RevokeInviteRequest
	(*RevokeInviteResponse)(nil),      // 24: fleetly.server.v1.RevokeInviteResponse
	(*timestamppb.Timestamp)(nil),     // 25: google.protobuf.Timestamp
}
var file_fleetly_server_v1_teams_proto_depIdxs = []int32{
	25, // 0: fleetly.server.v1.TeamView.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: fleetly.server.v1.CreateTeamResponse.team:type_name -> fleetly.server.v1.TeamView
	0,  // 2: fleetly.server.v1.ListTeamsResponse.teams:type_name -> fleetly.server.v1.TeamView
	0,  // 3: fleetly.server.v1.GetTeamResponse.team:type_name -> fleetly.server.v1.TeamView
	0,  // 4: fleetly.server.v1.UpdateTeamResponse.team:type_name -> fleetly.server.v1.TeamView
	25, // 5: fleetly.server.v1.TeamMemberView.created_at:type_name -> google.protobuf.Timestamp
	12, // 6: fleetly.server.v1.ListTeamMembersResponse.members:type_name -> fleetly.server.v1.TeamMemberView
	12, // 7: fleetly.server.v1.SetTeamMemberRoleResponse.member:type_name -> fleetly.server.v1.TeamMemberView
	25, // 8: fleetly.server.v1.InviteView.expires_at:type_name -> google.protobuf.Timestamp
	25, // 9: fleetly.server.v1.InviteView.created_at:type_name -> google.protobuf.Timestamp
	25, // 10: fleetly.server.v1.InviteView.accepted_at:type_name -> google.protobuf.Timestamp
	25, // 11: fleetly.server.v1.InviteView.revoked_at:type_name -> google.protobuf.Timestamp
	19, // 12: fleetly.server.v1.CreateInviteResponse.invite:type_name -> fleetly.server.v1.InviteView
	19, // 13: fleetly.server.v1.ListTeamInvitesResponse.invites:type_name -> fleetly.server.v1.InviteView
	1,  // 14: fleetly.server.v1.TeamsService.CreateTeam:input_type -> fleetly.server.v1.CreateTeamRequest
	3,  // 15: fleetly.server.v1.TeamsService.ListTeams:input_type -> fleetly.server.v1.ListTeamsRequest
	5,  // 16: fleetly.server.v1.TeamsService.GetTeam:input_type -> fleetly.server.v1.GetTeamRequest
	7,  // 17: fleetly.server.v1.TeamsService.UpdateTeam:input_type -> fleetly.server.v1.UpdateTeamRequest
	9,  // 18: fleetly.server.v1.TeamsService.DeleteTeam:input_type -> fleetly.server.v1.DeleteTeamRequest
	11, // 19: fleetly.server.v1.TeamsService.ListTeamMembers:input_type -> fleetly.server.v1.ListTeamMembersRequest
	14, // 20: fleetly.server.v1.TeamsService.SetTeamMemberRole:input_type -> fleetly.server.v1.SetTeamMemberRoleRequest
	16, // 21: fleetly.server.v1.TeamsService.RemoveTeamMember:input_type -> fleetly.server.v1.RemoveTeamMemberRequest
	18, // 22: fleetly.server.v1.TeamsService.CreateInvite:input_type -> fleetly.server.v1.CreateInviteRequest
	21, // 23: fleetly.server.v1.TeamsService.ListTeamInvites:input_type -> fleetly.server.v1.ListTeamInvitesRequest
	23, // 24: fleetly.server.v1.TeamsService.RevokeInvite:input_type -> fleetly.server.v1.RevokeInviteRequest
	2,  // 25: fleetly.server.v1.TeamsService.CreateTeam:output_type -> fleetly.server.v1.CreateTeamResponse
	4,  // 26: fleetly.server.v1.TeamsService.ListTeams:output_type -> fleetly.server.v1.ListTeamsResponse
	6,  // 27: fleetly.server.v1.TeamsService.GetTeam:output_type -> fleetly.server.v1.GetTeamResponse
	8,  // 28: fleetly.server.v1.TeamsService.UpdateTeam:output_type -> fleetly.server.v1.UpdateTeamResponse
	10, // 29: fleetly.server.v1.TeamsService.DeleteTeam:output_type -> fleetly.server.v1.DeleteTeamResponse
	13, // 30: fleetly.server.v1.TeamsService.ListTeamMembers:output_type -> fleetly.server.v1.ListTeamMembersResponse
	15, // 31: fleetly.server.v1.TeamsService.SetTeamMemberRole:output_type -> fleetly.server.v1.SetTeamMemberRoleResponse
	17, // 32: fleetly.server.v1.TeamsService.RemoveTeamMember:output_type -> fleetly.server.v1.RemoveTeamMemberResponse
	20, // 33: fleetly.server.v1.TeamsService.CreateInvite:output_type -> fleetly.server.v1.CreateInviteResponse
	22, // 34: fleetly.server.v1.TeamsService.ListTeamInvites:output_type -> fleetly.server.v1.ListTeamInvitesResponse
	24, // 35: fleetly.server.v1.TeamsService.RevokeInvite:output_type -> fleetly.server.v1.RevokeInviteResponse
	25, // [25:36] is the sub-list for method output_type
	14, // [14:25] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_fleetly_server_v1_teams_proto_init() }
func file_fleetly_server_v1_teams_proto_init() {
	if File_fleetly_server_v1_teams_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleetly_server_v1_teams_proto_rawDesc), len(file_fleetly_server_v1_teams_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleetly_server_v1_teams_proto_goTypes,
		DependencyIndexes: file_fleetly_server_v1_teams_proto_depIdxs,
		MessageInfos:      file_fleetly_server_v1_teams_proto_msgTypes,
	}.Build()
	File_fleetly_server_v1_teams_proto = out.File
	file_fleetly_server_v1_teams_proto_goTypes = nil
	file_fleetly_server_v1_teams_proto_depIdxs = nil
}
