// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: fleetly/server/v1/terminal.proto

package serverv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/fleetlyrun/fleetly/genproto/fleetly/annotations/v1"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTerminalTicketRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 目标应用名。
	App string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	// 目标服务名（app 内 compose 服务名；多副本时由控制面择 running 任务，
	// 副本细节对操作员透明——设计 §2.3）。
	Service       string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTerminalTicketRequest) Reset() {
	*x = CreateTerminalTicketRequest{}
	mi := &file_fleetly_server_v1_terminal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTerminalTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTerminalTicketRequest) ProtoMessage() {}

func (x *CreateTerminalTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_terminal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTerminalTicketRequest.ProtoReflect.Descriptor instead.
func (*CreateTerminalTicketRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_terminal_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTerminalTicketRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *CreateTerminalTicketRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type CreateTerminalTicketResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 一次性 ticket（随机 128bit URL-safe；60s 过期、单次使用）。
	Ticket string `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	// 过期时刻（UTC）。
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// WS 接入路径（相对 gateway 同源；Console 拼协议与 host）：
	// `/v1/terminal?ticket=<ticket>`。
	WebsocketPath string `protobuf:"bytes,3,opt,name=websocket_path,json=websocketPath,proto3" json:"websocket_path,omitempty"`
	// 有效秒数（60——与 expires_at 冗余的诚实倒计时面）。
	ExpiresInSeconds int32 `protobuf:"varint,4,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateTerminalTicketResponse) Reset() {
	*x = CreateTerminalTicketResponse{}
	mi := &file_fleetly_server_v1_terminal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTerminalTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTerminalTicketResponse) ProtoMessage() {}

func (x *CreateTerminalTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_terminal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTerminalTicketResponse.ProtoReflect.Descriptor instead.
func (*CreateTerminalTicketResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_terminal_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTerminalTicketResponse) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

func (x *CreateTerminalTicketResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CreateTerminalTicketResponse) GetWebsocketPath() string {
	if x != nil {
		return x.WebsocketPath
	}
	return ""
}

func (x *CreateTerminalTicketResponse) GetExpiresInSeconds() int32 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

type GetTerminalStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTerminalStatusRequest) Reset() {
	*x = GetTerminalStatusRequest{}
	mi := &file_fleetly_server_v1_terminal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTerminalStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTerminalStatusRequest) ProtoMessage() {}

func (x *GetTerminalStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_terminal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTerminalStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTerminalStatusRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_terminal_proto_rawDescGZIP(), []int{2}
}

type GetTerminalStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 终端功能是否启用（config terminal.enabled；false = 不部署 relay，
	// CreateTerminalTicket 报 E_TERMINAL_DISABLED）。
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// fleetly-exec relay 服务部署态（global 服务在位与否）。
	RelayDeployed bool `protobuf:"varint,2,opt,name=relay_deployed,json=relayDeployed,proto3" json:"relay_deployed,omitempty"`
	// relay 实况镜像引用（不在位为空）。
	RelayImage string `protobuf:"bytes,3,opt,name=relay_image,json=relayImage,proto3" json:"relay_image,omitempty"`
	// 已连接 relay 节点数（连接表大小——node liveness = 连接存在）。
	NodesConnected int32 `protobuf:"varint,4,opt,name=nodes_connected,json=nodesConnected,proto3" json:"nodes_connected,omitempty"`
	// 活跃终端会话数（全局——上限 8，per-token 上限 2）。
	ActiveSessions int32 `protobuf:"varint,5,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTerminalStatusResponse) Reset() {
	*x = GetTerminalStatusResponse{}
	mi := &file_fleetly_server_v1_terminal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTerminalStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTerminalStatusResponse) ProtoMessage() {}

func (x *GetTerminalStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_terminal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTerminalStatusResponse.ProtoReflect.Descriptor instead.
func (*GetTerminalStatusResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_terminal_proto_rawDescGZIP(), []int{3}
}

func (x *GetTerminalStatusResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GetTerminalStatusResponse) GetRelayDeployed() bool {
	if x != nil {
		return x.RelayDeployed
	}
	return false
}

func (x *GetTerminalStatusResponse) GetRelayImage() string {
	if x != nil {
		return x.RelayImage
	}
	return ""
}

func (x *GetTerminalStatusResponse) GetNodesConnected() int32 {
	if x != nil {
		return x.NodesConnected
	}
	return 0
}

func (x *GetTerminalStatusResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

var File_fleetly_server_v1_terminal_proto protoreflect.FileDescriptor

const file_fleetly_server_v1_terminal_proto_rawDesc = "" +
	"\n" +
	" fleetly/server/v1/terminal.proto\x12\x11fleetly.server.v1\x1a\x1bbuf/validate/validate.proto\x1a(fleetly/annotations/v1/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"a\n" +
	"\x1bCreateTerminalTicketRequest\x12\x1c\n" +
	"\x03app\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\x03app\x12$\n" +
	"\aservice\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\aservice\"\xc6\x01\n" +
	"\x1cCreateTerminalTicketResponse\x12\x16\n" +
	"\x06ticket\x18\x01 \x01(\tR\x06ticket\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12%\n" +
	"\x0ewebsocket_path\x18\x03 \x01(\tR\rwebsocketPath\x12,\n" +
	"\x12expires_in_seconds\x18\x04 \x01(\x05R\x10expiresInSeconds\"\x1a\n" +
	"\x18GetTerminalStatusRequest\"\xcf\x01\n" +
	"\x19GetTerminalStatusResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12%\n" +
	"\x0erelay_deployed\x18\x02 \x01(\bR\rrelayDeployed\x12\x1f\n" +
	"\vrelay_image\x18\x03 \x01(\tR\n" +
	"relayImage\x12'\n" +
	"\x0fnodes_connected\x18\x04 \x01(\x05R\x0enodesConnected\x12'\n" +
	"\x0factive_sessions\x18\x05 \x01(\x05R\x0eactiveSessions2\xce\x02\n" +
	"\vExecService\x12\xa4\x01\n" +
	"\x14CreateTerminalTicket\x12..fleetly.server.v1.CreateTerminalTicketRequest\x1a/.fleetly.server.v1.CreateTerminalTicketResponse\"+\x82\xb5\x18\bterminal\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/terminal/tickets\x12\x97\x01\n" +
	"\x11GetTerminalStatus\x12+.fleetly.server.v1.GetTerminalStatusRequest\x1a,.fleetly.server.v1.GetTerminalStatusResponse\"'\x82\xb5\x18\bterminal\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/terminal/statusB\x98\x01\x92ARRP\n" +
	"\adefault\x12E\n" +
	"\x1dAn unexpected error response.\x12$\n" +
	"\"\x1a .fleetly.shared.v1.ErrorResponseZAgithub.com/fleetlyrun/fleetly/genproto/fleetly/server/v1;serverv1b\x06proto3"

var (
	file_fleetly_server_v1_terminal_proto_rawDescOnce sync.Once
	file_fleetly_server_v1_terminal_proto_rawDescData []byte
)

func file_fleetly_server_v1_terminal_proto_rawDescGZIP() []byte {
	file_fleetly_server_v1_terminal_proto_rawDescOnce.Do(func() {
		file_fleetly_server_v1_terminal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleetly_server_v1_terminal_proto_rawDesc), len(file_fleetly_server_v1_terminal_proto_rawDesc)))
	})
	return file_fleetly_server_v1_terminal_proto_rawDescData
}

var file_fleetly_server_v1_terminal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_fleetly_server_v1_terminal_proto_goTypes = []any{
	(*CreateTerminalTicketRequest)(nil),  // 0: fleetly.server.v1.CreateTerminalTicketRequest
	(*CreateTerminalTicketResponse)(nil), // 1: fleetly.server.v1.CreateTerminalTicketResponse
	(*GetTerminalStatusRequest)(nil),     // 2: fleetly.server.v1.GetTerminalStatusRequest
	(*GetTerminalStatusResponse)(nil),    // 3: fleetly.server.v1.GetTerminalStatusResponse
	(*timestamppb.Timestamp)(nil),        // 4: google.protobuf.Timestamp
}
var file_fleetly_server_v1_terminal_proto_depIdxs = []int32{
	4, // 0: fleetly.server.v1.CreateTerminalTicketResponse.expires_at:type_name -> google.protobuf.Timestamp
	0, // 1: fleetly.server.v1.ExecService.CreateTerminalTicket:input_type -> fleetly.server.v1.CreateTerminalTicketRequest
	2, // 2: fleetly.server.v1.ExecService.GetTerminalStatus:input_type -> fleetly.server.v1.GetTerminalStatusRequest
	1, // 3: fleetly.server.v1.ExecService.CreateTerminalTicket:output_type -> fleetly.server.v1.CreateTerminalTicketResponse
	3, // 4: fleetly.server.v1.ExecService.GetTerminalStatus:output_type -> fleetly.server.v1.GetTerminalStatusResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fleetly_server_v1_terminal_proto_init() }
func file_fleetly_server_v1_terminal_proto_init() {
	if File_fleetly_server_v1_terminal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleetly_server_v1_terminal_proto_rawDesc), len(file_fleetly_server_v1_terminal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleetly_server_v1_terminal_proto_goTypes,
		DependencyIndexes: file_fleetly_server_v1_terminal_proto_depIdxs,
		MessageInfos:      file_fleetly_server_v1_terminal_proto_msgTypes,
	}.Build()
	File_fleetly_server_v1_terminal_proto = out.File
	file_fleetly_server_v1_terminal_proto_goTypes = nil
	file_fleetly_server_v1_terminal_proto_depIdxs = nil
}
